import { File } from 'expo-file-system';
import { supabase } from '@/lib/supabase';
import { getCurrentPortalProfile } from '@/services/profile';

export type CreditDispatchStatus = 'Draft' | 'Pending Accounts Approval' | 'Pending Manager Approval' | 'Approved' | 'Rejected by Accounts' | 'Rejected by Manager' | 'Correction Requested by Accounts' | 'Correction Requested by Manager';
export type RecoveryStatus = 'Pending Payment' | 'Partial Payment' | 'Partial Payment - Overdue' | 'Payment Overdue' | 'Closed';
export type CreditDispatch = { id:string; dispatch_no:string|null; branch:string; customer_name:string; customer_type:'Major Account'|'Retailer'|'Customer'; mobile_no:string; document_type:'DC'|'Tax Invoice'|'PI'; document_no:string|null; document_date:string; credit_amount:number; tentative_closure_days:7|15|30; due_date:string; total_received_amount:number; balance_amount:number; approval_status:CreditDispatchStatus; recovery_status:RecoveryStatus; remarks:string|null; rejection_reason:string|null; correction_note:string|null; customer_signature_path:string|null; issuer_signature_path:string|null; sales_employee_name:string|null; approved_by:string|null; approved_at:string|null; created_at:string; updated_at:string };
export type CreditPayment = { id:string; dispatch_id:string; received_amount:number; received_date:string; payment_mode:string; reference_no:string|null; remarks:string|null; created_at:string };
export type CreditEvent = { id:string; dispatch_id:string; event_type:string; event_note:string|null; created_by:string|null; created_at:string; actor_name:string|null };
export type CreditDispatchFormInput = { branch:string; customerName:string; customerType:CreditDispatch['customer_type']; mobileNo:string; documentType:CreditDispatch['document_type']; documentNo:string; documentDate:string; creditAmount:number; tentativeClosureDays:7|15|30; remarks:string; salesEmployeeName:string; customerSignatureUri:string; issuerSignatureUri:string };
export type CreditDispatchPaymentInput = { dispatchId:string; receivedAmount:number; receivedDate:string; paymentMode:'Cash'|'UPI'|'Bank'|'Cheque'|'Adjustment'|'Other'; referenceNo?:string; remarks?:string };
export type SalesEmployee = { id:string; name:string };

export function deriveRecovery(row:CreditDispatch):RecoveryStatus { if(row.approval_status!=='Approved') return row.recovery_status; const credit=Number(row.credit_amount??0),received=Number(row.total_received_amount??0),balance=Number(row.balance_amount??0); if(balance<=0||(credit>0&&received>=credit)) return 'Closed'; const pastDue=Boolean(row.due_date)&&row.due_date<new Date().toISOString().slice(0,10); if(received>0&&pastDue) return 'Partial Payment - Overdue'; if(received>0) return 'Partial Payment'; if(pastDue) return 'Payment Overdue'; return 'Pending Payment'; }
function normalize(row:CreditDispatch){ const recovery=deriveRecovery(row); return recovery===row.recovery_status?row:{...row,recovery_status:recovery}; }
export function calculateDueDate(documentDate:string,days:number){ if(!documentDate) return ''; return new Date(new Date(documentDate).getTime()+days*86400000).toISOString().slice(0,10); }
function validate(input:CreditDispatchFormInput){ if(!input.customerName.trim()) throw new Error('Customer name is required.'); if(!/^\d{10}$/.test(input.mobileNo.trim())) throw new Error('Enter a valid 10 digit mobile number.'); if(!input.documentNo.trim()) throw new Error('Document no. is required.'); if(!input.documentDate) throw new Error('Document date is required.'); if(!input.creditAmount||input.creditAmount<=0) throw new Error('Credit amount must be greater than zero.'); if(!input.salesEmployeeName.trim()) throw new Error('Sales employee name is required.'); if(!input.customerSignatureUri) throw new Error('Customer signature is required.'); if(!input.issuerSignatureUri) throw new Error('Issuing official signature is required.'); }
function normalizeName(value:string){ return value.trim().replace(/\s+/g,' ').toUpperCase(); }
async function ensureSalesEmployeeName(value:string){ const name=normalizeName(value); if(!name) throw new Error('Sales employee name is required.'); const {data:session}=await supabase.auth.getSession(); const {error}=await supabase.from('portal_sales_employees').upsert({name,is_active:true,created_by:session.session?.user.id??null},{onConflict:'name',ignoreDuplicates:true}); if(error) throw error; return name; }
export async function searchSalesEmployees(term:string):Promise<SalesEmployee[]>{ const query=normalizeName(term); if(query.length<2) return []; const {data,error}=await supabase.from('portal_sales_employees').select('id,name').eq('is_active',true).ilike('name',`%${query}%`).order('name').limit(12); if(error) throw error; return (data??[]) as SalesEmployee[]; }
async function uploadSignature(uri:string,type:'customer'|'issuer'){ const {data:session}=await supabase.auth.getSession(); const userId=session.session?.user.id??'unknown-user'; const path=`${userId}/${Date.now()}-${type}-signature.png`; const file=new File(uri); const bytes=await file.arrayBuffer(); const {error}=await supabase.storage.from('credit-dispatch-signatures').upload(path,bytes,{contentType:'image/png',upsert:false}); if(error) throw error; return path; }
async function addEvent(dispatchId:string,eventType:string,eventNote?:string){ const profile=await getCurrentPortalProfile(); const {error}=await supabase.from('portal_credit_dispatch_events').insert({dispatch_id:dispatchId,event_type:eventType,event_note:eventNote?.trim()||null,created_by:profile?.id??null}); if(error) throw error; }

export async function getCreditDispatches(limit=300):Promise<CreditDispatch[]>{ const {data,error}=await supabase.from('portal_credit_dispatches').select('*').order('created_at',{ascending:false}).limit(limit); if(error) throw error; return ((data??[]) as CreditDispatch[]).map(normalize); }
export async function getCreditDispatchDetail(dispatchId:string){ const [dispatchResult,paymentsResult,eventsResult]=await Promise.all([supabase.from('portal_credit_dispatches').select('*').eq('id',dispatchId).single(),supabase.from('portal_credit_dispatch_payments').select('*').eq('dispatch_id',dispatchId).order('received_date',{ascending:false}).order('created_at',{ascending:false}),supabase.from('portal_credit_dispatch_events').select('*').eq('dispatch_id',dispatchId).order('created_at',{ascending:false})]); if(dispatchResult.error) throw dispatchResult.error; if(paymentsResult.error) throw paymentsResult.error; if(eventsResult.error) throw eventsResult.error; const rawEvents=(eventsResult.data??[]) as Omit<CreditEvent,'actor_name'>[]; const ids=[...new Set(rawEvents.map((event)=>event.created_by).filter((id):id is string=>Boolean(id)))]; let names=new Map<string,string>(); if(ids.length){ const profiles=await supabase.from('portal_profiles').select('id,full_name').in('id',ids); if(!profiles.error) names=new Map((profiles.data??[]).map((profile)=>[String(profile.id),String(profile.full_name??'')])); } return {dispatch:normalize(dispatchResult.data as CreditDispatch),payments:(paymentsResult.data??[]) as CreditPayment[],events:rawEvents.map((event)=>({...event,actor_name:event.created_by?names.get(event.created_by)||null:null})) as CreditEvent[]}; }
export async function reviewCreditDispatch(dispatchId:string,action:'Approved'|'Rejected'|'Correction Required',note:string){ if((action==='Rejected'||action==='Correction Required')&&!note.trim()) throw new Error('A reason is required.'); const {error}=await supabase.rpc('portal_review_credit_dispatch',{p_dispatch_id:dispatchId,p_action:action,p_note:note.trim()||null}); if(error) throw error; }
export async function addCreditComment(dispatchId:string,note:string){ const value=note.trim(); if(!value) throw new Error('Enter a comment first.'); if(value.length>2000) throw new Error('Comment cannot exceed 2000 characters.'); const profile=await getCurrentPortalProfile(); if(!profile?.id||profile.is_active===false) throw new Error('Active portal user is required.'); const {error}=await supabase.from('portal_credit_dispatch_events').insert({dispatch_id:dispatchId,event_type:'Comment',event_note:value,created_by:profile.id}); if(error) throw error; }
export async function createCreditDispatch(input:CreditDispatchFormInput){ validate(input); const salesEmployeeName=await ensureSalesEmployeeName(input.salesEmployeeName); const customerPath=await uploadSignature(input.customerSignatureUri,'customer'); let issuerPath=''; try{ issuerPath=await uploadSignature(input.issuerSignatureUri,'issuer'); const now=new Date().toISOString(); const {data,error}=await supabase.from('portal_credit_dispatches').insert({branch:input.branch.trim().toUpperCase(),customer_name:input.customerName.trim().toUpperCase(),customer_type:input.customerType,mobile_no:input.mobileNo.trim(),document_type:input.documentType,document_no:input.documentNo.trim().toUpperCase(),document_date:input.documentDate,credit_amount:input.creditAmount,tentative_closure_days:input.tentativeClosureDays,due_date:calculateDueDate(input.documentDate,input.tentativeClosureDays),approval_status:'Pending Accounts Approval',remarks:input.remarks.trim().toUpperCase()||null,sales_employee_name:salesEmployeeName,customer_signature_path:customerPath,issuer_signature_path:issuerPath,customer_signed_at:now,issuer_signed_at:now}).select('*').single(); if(error) throw error; await addEvent(data.id,'Submitted for Accounts Approval','Credit dispatch request submitted digitally with customer and issuer signatures for Accounts approval.'); return data as CreditDispatch; } catch(error){ const paths=[customerPath,issuerPath].filter(Boolean); if(paths.length) await supabase.storage.from('credit-dispatch-signatures').remove(paths); throw error; } }
export async function resubmitCorrectedCreditDispatch(dispatchId:string,input:CreditDispatchFormInput,loggedInBranch:string){ validate(input); const current=(await getCreditDispatchDetail(dispatchId)).dispatch; if(!['Correction Requested by Accounts','Correction Requested by Manager'].includes(current.approval_status)) throw new Error('This request is no longer awaiting correction.'); const normalizeBranch=(value:string)=>value.trim().toUpperCase().replace(/[^A-Z0-9]/g,''); if(normalizeBranch(current.branch)!==normalizeBranch(loggedInBranch)) throw new Error('This request belongs to another branch.'); const salesEmployeeName=await ensureSalesEmployeeName(input.salesEmployeeName); const customerPath=await uploadSignature(input.customerSignatureUri,'customer'); let issuerPath=''; try{ issuerPath=await uploadSignature(input.issuerSignatureUri,'issuer'); const now=new Date().toISOString(); const {data,error}=await supabase.from('portal_credit_dispatches').update({customer_name:input.customerName.trim().toUpperCase(),customer_type:input.customerType,mobile_no:input.mobileNo.trim(),document_type:input.documentType,document_no:input.documentNo.trim().toUpperCase(),document_date:input.documentDate,credit_amount:input.creditAmount,tentative_closure_days:input.tentativeClosureDays,due_date:calculateDueDate(input.documentDate,input.tentativeClosureDays),remarks:input.remarks.trim().toUpperCase()||null,sales_employee_name:salesEmployeeName,customer_signature_path:customerPath,issuer_signature_path:issuerPath,customer_signed_at:now,issuer_signed_at:now,approval_status:'Pending Accounts Approval',correction_note:null,rejection_reason:null,approved_by:null,approved_at:null,updated_at:now}).eq('id',dispatchId).in('approval_status',['Correction Requested by Accounts','Correction Requested by Manager']).eq('branch',current.branch).select('*').single(); if(error) throw error; await addEvent(dispatchId,'Corrected and Resubmitted to Accounts','Branch corrected the request, captured fresh signatures, and resubmitted it for Accounts approval.'); return data as CreditDispatch; } catch(error){ const paths=[customerPath,issuerPath].filter(Boolean); if(paths.length) await supabase.storage.from('credit-dispatch-signatures').remove(paths); throw error; } }
export async function addCreditDispatchPayment(input:CreditDispatchPaymentInput){ const amount=Number(input.receivedAmount??0); if(!amount||amount<=0) throw new Error('Enter a valid received amount.'); if(!input.receivedDate) throw new Error('Received date is required.'); const {data,error:readError}=await supabase.from('portal_credit_dispatches').select('*').eq('id',input.dispatchId).single(); if(readError) throw readError; const record=normalize(data as CreditDispatch); if(record.approval_status!=='Approved') throw new Error('Payment can be added only after manager approval.'); if(record.recovery_status==='Closed') throw new Error('This request is already closed.'); if(amount>Number(record.balance_amount??0)) throw new Error('Received amount cannot be greater than balance amount.'); const {error}=await supabase.from('portal_credit_dispatch_payments').insert({dispatch_id:input.dispatchId,received_amount:amount,received_date:input.receivedDate,payment_mode:input.paymentMode,reference_no:input.referenceNo?.trim()||null,remarks:input.remarks?.trim()||null}); if(error) throw error; await addEvent(input.dispatchId,'Payment Added',`${formatCreditMoney(amount)} received on ${input.receivedDate}. ${input.remarks??''}`); }
export async function getCreditSignatureUrl(path:string){ const {data,error}=await supabase.storage.from('credit-dispatch-signatures').createSignedUrl(path,900); if(error) throw error; if(!data?.signedUrl) throw new Error('Could not open signature.'); return data.signedUrl; }
export function formatCreditMoney(value:number|null|undefined){ return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value??0)); }
