import { supabase } from '@/lib/supabase';

export type ManagerInventoryRow = {
  id: string; branch_key: string | null; branch_code: string; branch_name: string | null; item_code: string; item_name: string | null;
  item_group: string | null; uom: string | null; dnp: number | null; qty: number | null; inv_value: number | null; report_date: string | null;
};
export type ManagerInventoryTxnRow = ManagerInventoryRow & { received: number | null; issued: number | null; closing_balance: number | null; closing_value: number | null };

type PortalInventoryTxnRow = Omit<ManagerInventoryTxnRow, 'received'|'issued'|'qty'|'inv_value'> & { received_qty:number|null; issued_qty:number|null; closing_balance:number|null; closing_value:number|null };

function cleanPartSearch(search:string) { return search.trim().replace(/\s+/g,'').toUpperCase(); }
async function resolveBranchKey(value:string) { const input=value.trim(); if(!input) return ''; const {data,error}=await supabase.rpc('resolve_portal_branch',{value:input}); return error ? input.toUpperCase() : String(data ?? '').trim() || input.toUpperCase(); }
async function branchScope(branch:string) { const resolved=await resolveBranchKey(branch); if(!resolved) return [] as string[]; const {data:selected}=await supabase.from('portal_branches').select('head_quarter').eq('branch_key',resolved).maybeSingle(); if(!selected?.head_quarter) return [resolved]; const {data}=await supabase.from('portal_branches').select('branch_key').eq('head_quarter',selected.head_quarter).eq('is_active',true); const rows=(data ?? []) as Array<{branch_key:string}>; return rows.length ? [...new Set(rows.map((row)=>row.branch_key))] : [resolved]; }

export async function getLatestInventoryReportDate() { const {data,error}=await supabase.from('portal_inventory_staging').select('report_date').order('report_date',{ascending:false}).limit(1).maybeSingle(); if(error) return null; return data?.report_date ?? null; }
export async function getInventoryBranches(reportDate='') { let query=supabase.from('portal_inventory_staging').select('branch_key,branch_code,branch_name').limit(500); if(reportDate) query=query.eq('report_date',reportDate); const {data,error}=await query; if(error) throw error; const map=new Map<string,{key:string;label:string}>(); for(const row of data ?? []) { const key=String(row.branch_key ?? row.branch_code ?? '').trim(); if(key) map.set(key,{key,label:row.branch_name ? `${row.branch_name} (${row.branch_code})` : key}); } return [...map.values()].sort((a,b)=>a.label.localeCompare(b.label)); }
export async function getManagerInventoryLookup(search='',branch='all',reportDate='') { const term=cleanPartSearch(search); if(!term) return [] as ManagerInventoryRow[]; const latest=reportDate || await getLatestInventoryReportDate(); const scope=branch==='all'?[]:await branchScope(branch); let query:any=supabase.from('portal_inventory_staging').select('id,report_date,branch_key,branch_code,branch_name,item_code,item_name,item_group,uom,dnp,closing_balance,closing_value').order('branch_key').order('item_code').limit(300); if(latest) query=query.eq('report_date',latest); if(branch!=='all') query=scope.length?query.in('branch_key',scope):query.eq('branch_key',branch); query=query.ilike('item_code',`%${term}%`); const {data,error}=await query; if(error) throw error; return (data ?? []).map((row:any)=>({id:row.id,branch_key:row.branch_key,branch_code:row.branch_code,branch_name:row.branch_name,item_code:row.item_code,item_name:row.item_name,item_group:row.item_group,uom:row.uom,dnp:row.dnp,qty:row.closing_balance,inv_value:row.closing_value,report_date:row.report_date})) as ManagerInventoryRow[]; }
export async function getManagerInventoryTransactions(search='',branch='all',reportDate='') { const term=cleanPartSearch(search); if(!term) return [] as ManagerInventoryTxnRow[]; const latest=reportDate || await getLatestInventoryReportDate(); const scope=branch==='all'?[]:await branchScope(branch); let query:any=supabase.from('portal_inventory_staging').select('id,report_date,branch_key,branch_code,branch_name,item_code,item_name,item_group,uom,dnp,received_qty,issued_qty,closing_balance,closing_value').order('branch_key').order('item_code').limit(300); if(latest) query=query.eq('report_date',latest); if(branch!=='all') query=scope.length?query.in('branch_key',scope):query.eq('branch_key',branch); query=query.ilike('item_code',`%${term}%`).or('received_qty.neq.0,issued_qty.neq.0'); const {data,error}=await query; if(error) throw error; return ((data ?? []) as PortalInventoryTxnRow[]).map((row)=>({...row,qty:row.closing_balance,inv_value:row.closing_value,received:row.received_qty,issued:row.issued_qty})); }
