import { useRef, useState, type ReactNode } from 'react';
import DateTimePicker from '@react-native-community/datetimepicker';
import { useQuery } from '@tanstack/react-query';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SignaturePad, type SignaturePadHandle } from '@/components/SignaturePad';
import { searchCreditCustomers } from '@/services/creditCustomers';
import { calculateDueDate, searchSalesEmployees, type CreditDispatch, type CreditDispatchFormInput } from '@/services/creditDispatch';
import { colors, radius, spacing } from '@/theme/tokens';

export type CreditFormSeed = { customerName?:string; customerType?:CreditDispatch['customer_type']; mobileNo?:string; documentType?:CreditDispatch['document_type']; documentNo?:string; documentDate?:string; creditAmount?:number; tentativeClosureDays?:7|15|30; remarks?:string; salesEmployeeName?:string };
export function CreditDispatchForm({branch,initial={},busy=false,submitLabel='Submit for Accounts Approval',onSubmit}:{branch:string;initial?:CreditFormSeed;busy?:boolean;submitLabel?:string;onSubmit:(input:CreditDispatchFormInput)=>Promise<void>}){
 const [customerName,setCustomerName]=useState(initial.customerName??''); const [customerType,setCustomerType]=useState<CreditDispatch['customer_type']>(initial.customerType??'Customer'); const [mobileNo,setMobileNo]=useState(initial.mobileNo??''); const [documentType,setDocumentType]=useState<CreditDispatch['document_type']>(initial.documentType??'DC'); const [documentNo,setDocumentNo]=useState(initial.documentNo??''); const [documentDate,setDocumentDate]=useState(initial.documentDate??new Date().toISOString().slice(0,10)); const [creditAmount,setCreditAmount]=useState(initial.creditAmount?String(initial.creditAmount):''); const [days,setDays]=useState<7|15|30>(initial.tentativeClosureDays??7); const [remarks,setRemarks]=useState(initial.remarks??''); const [salesEmployee,setSalesEmployee]=useState(initial.salesEmployeeName??''); const [showDate,setShowDate]=useState(false); const [message,setMessage]=useState('');
 const customerSig=useRef<SignaturePadHandle>(null); const issuerSig=useRef<SignaturePadHandle>(null);
 const customerQuery=useQuery({queryKey:['credit-customer-search',customerName],queryFn:()=>searchCreditCustomers(customerName),enabled:customerName.trim().length>=2,staleTime:15_000});
 const employeeQuery=useQuery({queryKey:['credit-sales-search',salesEmployee],queryFn:()=>searchSalesEmployees(salesEmployee),enabled:salesEmployee.trim().length>=2,staleTime:15_000});
 async function submit(){ setMessage(''); try{ const amount=Number(creditAmount.replace(/,/g,'')); const customerSignatureUri=await customerSig.current?.capture(); const issuerSignatureUri=await issuerSig.current?.capture(); if(!customerSignatureUri||!issuerSignatureUri) throw new Error('Both signatures are required.'); await onSubmit({branch,customerName,customerType,mobileNo,documentType,documentNo,documentDate,creditAmount:amount,tentativeClosureDays:days,remarks,salesEmployeeName:salesEmployee,customerSignatureUri,issuerSignatureUri}); }catch(error){ setMessage(error instanceof Error?error.message:'Could not submit request.'); } }
 return <View style={styles.form}>
   <Field label="Branch"><View style={styles.readonly}><Text style={styles.readonlyText}>{branch}</Text></View></Field>
   <Field label="Customer name"><TextInput value={customerName} onChangeText={(v)=>setCustomerName(v.toUpperCase())} placeholder="Customer name" placeholderTextColor={colors.textMuted} style={styles.input}/>{customerName.trim().length>=2&&(customerQuery.data??[]).length?<View style={styles.suggestions}>{(customerQuery.data??[]).map((item)=><Pressable key={item.customer_id} onPress={()=>{setCustomerName(item.customer_name);setMobileNo(item.mobile_no);setCustomerType(item.customer_type);}} style={styles.suggestion}><Text style={styles.suggestionTitle}>{item.customer_name}</Text><Text style={styles.suggestionMeta}>{item.mobile_no} • Outstanding ₹{Number(item.outstanding||0).toLocaleString('en-IN')} • {item.risk_category}</Text></Pressable>)}</View>:null}</Field>
   <Field label="Customer type"><View style={styles.chips}>{(['Major Account','Retailer','Customer'] as const).map((value)=><Choice key={value} label={value} active={customerType===value} onPress={()=>setCustomerType(value)}/>)}</View></Field>
   <Field label="Mobile"><TextInput value={mobileNo} onChangeText={(v)=>setMobileNo(v.replace(/\D/g,'').slice(0,10))} keyboardType="phone-pad" placeholder="10 digit mobile" placeholderTextColor={colors.textMuted} style={styles.input}/></Field>
   <Field label="Document type"><View style={styles.chips}>{(['DC','Tax Invoice','PI'] as const).map((value)=><Choice key={value} label={value} active={documentType===value} onPress={()=>setDocumentType(value)}/>)}</View></Field>
   <Field label="Document no."><TextInput value={documentNo} onChangeText={(v)=>setDocumentNo(v.toUpperCase())} placeholder="Document number" placeholderTextColor={colors.textMuted} style={styles.input}/></Field>
   <View style={styles.two}><View style={styles.half}><Field label="Document date"><Pressable onPress={()=>setShowDate(true)} style={styles.inputButton}><Text style={styles.inputButtonText}>{documentDate}</Text></Pressable></Field></View><View style={styles.half}><Field label="Credit amount"><TextInput value={creditAmount} onChangeText={(v)=>setCreditAmount(v.replace(/[^0-9.]/g,''))} keyboardType="decimal-pad" placeholder="₹0" placeholderTextColor={colors.textMuted} style={styles.input}/></Field></View></View>
   {showDate?<DateTimePicker value={new Date(`${documentDate}T00:00:00`)} mode="date" onChange={(_,date)=>{setShowDate(false);if(date)setDocumentDate(date.toISOString().slice(0,10));}}/>:null}
   <Field label="Tentative closure"><View style={styles.chips}>{([7,15,30] as const).map((value)=><Choice key={value} label={`${value} days`} active={days===value} onPress={()=>setDays(value)}/>)}</View><Text style={styles.helper}>Due date: {calculateDueDate(documentDate,days)}</Text></Field>
   <Field label="Sales employee"><TextInput value={salesEmployee} onChangeText={(v)=>setSalesEmployee(v.toUpperCase())} placeholder="Sales employee" placeholderTextColor={colors.textMuted} style={styles.input}/>{salesEmployee.trim().length>=2&&(employeeQuery.data??[]).length?<View style={styles.suggestions}>{(employeeQuery.data??[]).map((item)=><Pressable key={item.id} onPress={()=>setSalesEmployee(item.name)} style={styles.suggestion}><Text style={styles.suggestionTitle}>{item.name}</Text></Pressable>)}</View>:null}</Field>
   <Field label="Remarks"><TextInput value={remarks} onChangeText={(v)=>setRemarks(v.toUpperCase())} multiline placeholder="Optional remarks" placeholderTextColor={colors.textMuted} style={[styles.input,styles.textarea]}/></Field>
   <SignaturePad ref={customerSig} label="Customer signature"/><SignaturePad ref={issuerSig} label="Issuing official signature"/>
   {message?<Text style={styles.error}>{message}</Text>:null}
   <Pressable disabled={busy} onPress={()=>void submit()} style={[styles.submit,busy&&styles.disabled]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.submitText}>{submitLabel}</Text>}</Pressable>
 </View>
}
function Field({label,children}:{label:string;children:ReactNode}){return <View style={styles.field}><Text style={styles.label}>{label}</Text>{children}</View>}
function Choice({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.choice,active&&styles.choiceActive]}><Text style={[styles.choiceText,active&&styles.choiceTextActive]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({form:{gap:spacing.lg},field:{gap:spacing.sm},label:{color:colors.text,fontSize:11,fontWeight:'900'},input:{minHeight:48,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,paddingHorizontal:spacing.md,color:colors.text,fontSize:13,fontWeight:'700'},textarea:{minHeight:88,paddingTop:spacing.md,textAlignVertical:'top'},readonly:{minHeight:48,justifyContent:'center',paddingHorizontal:spacing.md,borderRadius:radius.md,backgroundColor:colors.surfaceMuted},readonlyText:{color:colors.text,fontSize:13,fontWeight:'900'},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},choice:{minHeight:42,justifyContent:'center',paddingHorizontal:12,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},choiceActive:{backgroundColor:colors.navy,borderColor:colors.navy},choiceText:{color:colors.textMuted,fontSize:11,fontWeight:'800'},choiceTextActive:{color:'#fff'},two:{flexDirection:'row',gap:spacing.sm},half:{flex:1},inputButton:{minHeight:48,justifyContent:'center',paddingHorizontal:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},inputButtonText:{color:colors.text,fontSize:12,fontWeight:'800'},helper:{color:colors.textMuted,fontSize:10,fontWeight:'700'},suggestions:{borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,overflow:'hidden'},suggestion:{padding:spacing.md,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},suggestionTitle:{color:colors.text,fontSize:11,fontWeight:'900'},suggestionMeta:{color:colors.textMuted,fontSize:9,marginTop:2},error:{color:colors.danger,fontSize:11,fontWeight:'700'},submit:{minHeight:52,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.navy},submitText:{color:'#fff',fontSize:12,fontWeight:'900'},disabled:{opacity:.5}});
