import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { Screen } from '@/components/Screen';
import { formatMoney } from '@/services/orders';
import { getInventoryBranches, getLatestInventoryReportDate, getManagerInventoryLookup, getManagerInventoryTransactions } from '@/services/managerInventory';
import { colors, radius, spacing } from '@/theme/tokens';

export default function ManagerDashboardScreen() {
  const { role } = useAuth();
  const allowed = role === 'manager' || role === 'developer';
  const [search,setSearch]=useState('');
  const [branch,setBranch]=useState('all');
  const latest=useQuery({queryKey:['manager-inventory-latest-date'],queryFn:getLatestInventoryReportDate,enabled:allowed});
  const reportDate=latest.data ?? '';
  const branches=useQuery({queryKey:['manager-inventory-branches',reportDate],queryFn:()=>getInventoryBranches(reportDate),enabled:allowed && !!reportDate});
  const hasSearch=search.trim().length>0;
  const inventory=useQuery({queryKey:['manager-inventory',search,branch,reportDate],queryFn:()=>getManagerInventoryLookup(search,branch,reportDate),enabled:allowed && hasSearch});
  const txns=useQuery({queryKey:['manager-inventory-txn',search,branch,reportDate],queryFn:()=>getManagerInventoryTransactions(search,branch,reportDate),enabled:allowed && hasSearch});
  const totals=useMemo(()=>({qty:(inventory.data??[]).reduce((sum,row)=>sum+Number(row.qty??0),0),value:(inventory.data??[]).reduce((sum,row)=>sum+Number(row.inv_value??0),0),received:(txns.data??[]).reduce((sum,row)=>sum+Number(row.received??0),0),issued:(txns.data??[]).reduce((sum,row)=>sum+Number(row.issued??0),0)}),[inventory.data,txns.data]);
  if(!allowed) return <View style={styles.center}><Text style={styles.error}>Manager Dashboard is available only to Manager and Developer roles.</Text></View>;
  return <Screen title="Manager Dashboard" subtitle={`Inventory position and movement${reportDate ? ` • ${reportDate}` : ''}`}>
    <TextInput value={search} onChangeText={setSearch} placeholder="Enter part number" autoCapitalize="characters" placeholderTextColor={colors.textMuted} style={styles.input}/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><Pressable onPress={()=>setBranch('all')} style={[styles.chip,branch==='all'&&styles.chipActive]}><Text style={[styles.chipText,branch==='all'&&styles.chipTextActive]}>All Branches</Text></Pressable>{(branches.data??[]).map((item)=><Pressable key={item.key} onPress={()=>setBranch(item.key)} style={[styles.chip,branch===item.key&&styles.chipActive]}><Text style={[styles.chipText,branch===item.key&&styles.chipTextActive]}>{item.label}</Text></Pressable>)}</ScrollView>
    {hasSearch ? <View style={styles.metrics}><Metric label="Closing Qty" value={String(totals.qty)} /><Metric label="Inventory Value" value={formatMoney(totals.value)} /><Metric label="Received" value={String(totals.received)} /><Metric label="Issued" value={String(totals.issued)} /></View> : <View style={styles.note}><Text style={styles.noteTitle}>Search inventory</Text><Text style={styles.noteText}>Enter a part number to see current stock and movement across branches.</Text></View>}
    {(inventory.isLoading||txns.isLoading)&&hasSearch ? <ActivityIndicator color={colors.navy}/> : null}
    {(inventory.data??[]).map((row)=><View key={row.id} style={styles.card}><View style={styles.top}><View style={styles.copy}><Text style={styles.part}>{row.item_code}</Text><Text style={styles.desc}>{row.item_name||'No description'}</Text></View><Text style={styles.qty}>{Number(row.qty??0)}</Text></View><View style={styles.grid}><Mini label="Branch" value={row.branch_name||row.branch_key||row.branch_code}/><Mini label="Group" value={row.item_group||'—'}/><Mini label="DNP" value={formatMoney(Number(row.dnp??0))}/><Mini label="Value" value={formatMoney(Number(row.inv_value??0))}/></View></View>)}
    {hasSearch && !inventory.isLoading && (inventory.data??[]).length===0 ? <Text style={styles.empty}>No inventory rows found for this part.</Text> : null}
    {hasSearch && (txns.data??[]).length ? <><Text style={styles.section}>Movement</Text>{(txns.data??[]).map((row)=><View key={`txn-${row.id}`} style={styles.card}><Text style={styles.part}>{row.item_code} • {row.branch_name||row.branch_code}</Text><View style={styles.grid}><Mini label="Received" value={String(Number(row.received??0))}/><Mini label="Issued" value={String(Number(row.issued??0))}/><Mini label="Closing" value={String(Number(row.closing_balance??0))}/><Mini label="Value" value={formatMoney(Number(row.closing_value??0))}/></View></View>)}</> : null}
  </Screen>;
}
function Metric({label,value}:{label:string;value:string}){return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>}
function Mini({label,value}:{label:string;value:string}){return <View style={styles.mini}><Text style={styles.miniLabel}>{label}</Text><Text numberOfLines={1} style={styles.miniValue}>{value}</Text></View>}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.xl,backgroundColor:colors.background},error:{color:colors.danger,textAlign:'center'},input:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface,paddingHorizontal:spacing.md,color:colors.text,fontSize:14,fontWeight:'700'},chips:{gap:spacing.sm,paddingRight:spacing.lg},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:999,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},chipActive:{backgroundColor:colors.navy,borderColor:colors.navy},chipText:{color:colors.textMuted,fontSize:11,fontWeight:'800'},chipTextActive:{color:'#fff'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},metric:{width:'48%',padding:spacing.md,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},metricLabel:{color:colors.textMuted,fontSize:10,fontWeight:'700'},metricValue:{color:colors.text,fontSize:17,fontWeight:'900',marginTop:3},note:{padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.blueSoft},noteTitle:{color:colors.navy,fontWeight:'900'},noteText:{color:colors.navySoft,fontSize:11,lineHeight:17,marginTop:3},card:{padding:spacing.md,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,gap:spacing.sm},top:{flexDirection:'row',justifyContent:'space-between',gap:spacing.md},copy:{flex:1},part:{color:colors.text,fontWeight:'900',fontSize:13},desc:{color:colors.textMuted,fontSize:11,marginTop:2},qty:{color:colors.blue,fontWeight:'900',fontSize:20},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},mini:{width:'47%'},miniLabel:{color:colors.textMuted,fontSize:9,fontWeight:'700'},miniValue:{color:colors.text,fontSize:11,fontWeight:'800',marginTop:2},section:{color:colors.text,fontSize:14,fontWeight:'900',marginTop:spacing.xs},empty:{color:colors.textMuted,textAlign:'center',paddingVertical:spacing.xl}});
