import { useMemo, useState } from 'react';
import { router } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { StatusChip } from '@/components/StatusChip';
import { formatMoney, getVisibleOrders } from '@/services/orders';
import { colors, radius, spacing } from '@/theme/tokens';

export default function ReportsScreen(){
 const [branch,setBranch]=useState('all'); const [status,setStatus]=useState('all');
 const query=useQuery({queryKey:['mobile-reports-orders'],queryFn:()=>getVisibleOrders(1000)}); const orders=query.data??[];
 const branches=useMemo(()=>[...new Set(orders.map((o)=>o.branch).filter((v):v is string=>Boolean(v)))].sort(),[orders]);
 const statuses=useMemo(()=>[...new Set(orders.map((o)=>o.status||o.approval_status).filter((v):v is string=>Boolean(v)))].sort(),[orders]);
 const filtered=useMemo(()=>orders.filter((o)=>(branch==='all'||o.branch===branch)&&(status==='all'||(o.status||o.approval_status)===status)),[orders,branch,status]);
 const branchSummary=useMemo(()=>Object.entries(filtered.reduce<Record<string,number>>((acc,o)=>{const key=o.branch||'Unassigned';acc[key]=(acc[key]||0)+1;return acc;},{})).sort((a,b)=>b[1]-a[1]),[filtered]);
 const statusSummary=useMemo(()=>Object.entries(filtered.reduce<Record<string,number>>((acc,o)=>{const key=o.status||o.approval_status||'Unknown';acc[key]=(acc[key]||0)+1;return acc;},{})).sort((a,b)=>b[1]-a[1]),[filtered]);
 const totalValue=filtered.reduce((sum,o)=>sum+Number(o.total_value??0),0); const totalQty=filtered.reduce((sum,o)=>sum+Number(o.total_qty??0),0);
 return <Screen title="Reports" subtitle="Operational order summaries with branch and status filters">
   <Text style={styles.label}>Branch</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><Chip label="All" active={branch==='all'} onPress={()=>setBranch('all')}/>{branches.map((value)=><Chip key={value} label={value} active={branch===value} onPress={()=>setBranch(value)}/>)}</ScrollView>
   <Text style={styles.label}>Status</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}><Chip label="All" active={status==='all'} onPress={()=>setStatus('all')}/>{statuses.map((value)=><Chip key={value} label={value} active={status===value} onPress={()=>setStatus(value)}/>)}</ScrollView>
   <View style={styles.metrics}><Metric label="Filtered" value={String(filtered.length)}/><Metric label="Qty" value={String(totalQty)}/><Metric label="Value" value={formatMoney(totalValue)}/><Metric label="Branches" value={String(branchSummary.length)}/></View>
   <View style={styles.summary}><Text style={styles.section}>Branch Summary</Text>{branchSummary.map(([label,count])=><View key={label} style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{count}</Text></View>)}</View>
   <View style={styles.summary}><Text style={styles.section}>Status Summary</Text>{statusSummary.map(([label,count])=><View key={label} style={styles.row}><StatusChip status={label}/><Text style={styles.rowValue}>{count}</Text></View>)}</View>
   <Text style={styles.section}>Orders</Text>{filtered.slice(0,100).map((order)=><Pressable key={order.id} onPress={()=>router.push(`/orders/${order.id}`)} style={({pressed})=>[styles.card,pressed&&styles.pressed]}><View style={styles.top}><View style={styles.copy}><Text style={styles.orderNo}>{order.final_order_no||order.order_no}</Text><Text style={styles.muted}>{order.customer_name||order.order_for||'—'} • {order.branch||'—'}</Text></View><StatusChip status={order.status||order.approval_status}/></View><View style={styles.cardMeta}><Text style={styles.muted}>Qty {Number(order.total_qty??0)}</Text><Text style={styles.muted}>{formatMoney(order.total_value)}</Text></View></Pressable>)}
   {!query.isLoading&&filtered.length===0?<Text style={styles.empty}>No orders match these filters.</Text>:null}
 </Screen>
}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,active&&styles.chipActive]}><Text style={[styles.chipText,active&&styles.chipTextActive]}>{label}</Text></Pressable>}
function Metric({label,value}:{label:string;value:string}){return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text numberOfLines={1} style={styles.metricValue}>{value}</Text></View>}
const styles=StyleSheet.create({label:{color:colors.textMuted,fontSize:10,fontWeight:'800',textTransform:'uppercase'},chips:{gap:spacing.sm,paddingRight:spacing.lg},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:999,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},chipActive:{backgroundColor:colors.navy,borderColor:colors.navy},chipText:{color:colors.textMuted,fontSize:11,fontWeight:'800'},chipTextActive:{color:'#fff'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},metric:{width:'48%',padding:spacing.md,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},metricLabel:{color:colors.textMuted,fontSize:10,fontWeight:'700'},metricValue:{color:colors.text,fontSize:17,fontWeight:'900',marginTop:2},summary:{padding:spacing.md,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},section:{color:colors.text,fontSize:14,fontWeight:'900'},row:{minHeight:40,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.border,marginTop:spacing.sm,paddingTop:spacing.sm},rowLabel:{flex:1,color:colors.text,fontSize:11,fontWeight:'700'},rowValue:{color:colors.navy,fontSize:13,fontWeight:'900'},card:{padding:spacing.md,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,gap:spacing.sm},pressed:{opacity:.8},top:{flexDirection:'row',justifyContent:'space-between',gap:spacing.sm},copy:{flex:1},orderNo:{color:colors.text,fontSize:13,fontWeight:'900'},muted:{color:colors.textMuted,fontSize:10,fontWeight:'700'},cardMeta:{flexDirection:'row',justifyContent:'space-between'},empty:{color:colors.textMuted,textAlign:'center',padding:spacing.xl}});
