import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ActivityIndicator, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { AppIcon } from '@/components/AppIcon';
import { Screen } from '@/components/Screen';
import { StateView } from '@/components/StateView';
import { StatusChip } from '@/components/StatusChip';
import { formatDate, formatMoney, type OrderSummary } from '@/services/orders';
import { getApprovedAdminOrders, processApprovedOrder, rejectApprovedOrder } from '@/services/operations';
import { colors, radius, spacing } from '@/theme/tokens';

type Action='process'|'reject'|null;
export default function AdminApprovedOrdersScreen(){
 const {role}=useAuth(); const allowed=role==='admin'||role==='developer'; const qc=useQueryClient(); const query=useQuery({queryKey:['admin-approved-orders'],queryFn:getApprovedAdminOrders,enabled:allowed}); const [search,setSearch]=useState(''); const [selected,setSelected]=useState<OrderSummary|null>(null); const [action,setAction]=useState<Action>(null); const [finalNo,setFinalNo]=useState(''); const [notes,setNotes]=useState(''); const [message,setMessage]=useState('');
 const visible=useMemo(()=>{const n=search.trim().toLowerCase();return (query.data??[]).filter(r=>!n||[r.order_no,r.final_order_no,r.branch,r.customer_name,r.machine_no,r.order_type].some(v=>String(v??'').toLowerCase().includes(n)));},[query.data,search]);
 const process=useMutation({mutationFn:()=>processApprovedOrder(selected!,finalNo,notes),onSuccess:async()=>{setMessage(`${selected?.order_no} processed.`);close();await query.refetch();await qc.invalidateQueries({queryKey:['orders']});},onError:e=>setMessage(e instanceof Error?e.message:'Processing failed.')});
 const reject=useMutation({mutationFn:()=>rejectApprovedOrder(selected!.id,notes),onSuccess:async()=>{setMessage(`${selected?.order_no} rejected.`);close();await query.refetch();await qc.invalidateQueries({queryKey:['orders']});},onError:e=>setMessage(e instanceof Error?e.message:'Reject failed.')});
 function close(){setSelected(null);setAction(null);setFinalNo('');setNotes('');}
 if(!allowed)return <View style={styles.center}><Text style={styles.error}>Approved Orders is available to Admin and Developer only.</Text></View>;
 return <Screen title="Approved Orders" subtitle={`${visible.length} approved order(s) ready for processing`} scroll={false}><FlatList data={visible} keyExtractor={i=>i.id} refreshing={query.isRefetching} onRefresh={()=>void query.refetch()} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><View style={styles.search}><AppIcon name="search" size={18} color={colors.textMuted}/><TextInput value={search} onChangeText={setSearch} placeholder="Order, branch, customer, machine…" placeholderTextColor={colors.textMuted} style={styles.searchInput}/></View>{message?<Text style={styles.message}>{message}</Text>:null}</View>} renderItem={({item})=><Pressable onPress={()=>router.push(`/orders/${item.id}`)} style={({pressed})=>[styles.card,pressed&&styles.pressed]}><View style={styles.top}><View style={styles.copy}><Text style={styles.no}>{item.final_order_no||item.order_no}</Text><Text style={styles.customer}>{item.customer_name||item.order_for||'Order'} · {item.branch}</Text></View><StatusChip status={item.status}/></View><View style={styles.grid}><Mini label="Type" value={item.order_type||'—'}/><Mini label="Qty" value={item.total_qty==null?'—':String(item.total_qty)}/><Mini label="Value" value={formatMoney(item.total_value)}/><Mini label="Created" value={formatDate(item.created_at)}/></View><View style={styles.actions}><Pressable onPress={e=>{e.stopPropagation();setSelected(item);setAction('process')}} style={styles.process}><Text style={styles.processText}>Process</Text></Pressable><Pressable onPress={e=>{e.stopPropagation();setSelected(item);setAction('reject')}} style={styles.reject}><Text style={styles.rejectText}>Reject</Text></Pressable></View></Pressable>} ListEmptyComponent={!query.isLoading?(query.isError?<StateView icon="alert" tone="error" title="Approved Orders could not be loaded" actionLabel="Retry" onAction={()=>void query.refetch()}/>:<StateView icon="check" title={search?'No matching approved orders':'Approved queue is clear'} message={search?'Try another order, branch, customer or machine.':'No approved orders are waiting for Admin processing.'}/>):null}/>
 <Modal visible={Boolean(action&&selected)} transparent animationType="fade" onRequestClose={close}><View style={styles.modalBackdrop}><View style={styles.dialog}><Text style={styles.dialogTitle}>{action==='process'?'Process approved order':'Reject approved order'}</Text><Text style={styles.dialogText}>{selected?.order_no} · {selected?.branch}</Text>{action==='process'?<><Text style={styles.label}>Final / DBMS Order No.</Text><TextInput autoCapitalize="characters" value={finalNo} onChangeText={setFinalNo} placeholder="Required" placeholderTextColor={colors.textMuted} style={styles.input}/></>:null}<Text style={styles.label}>{action==='process'?'Processing Notes':'Reason'}</Text><TextInput multiline value={notes} onChangeText={setNotes} placeholder={action==='reject'?'Reason for rejection':'Optional notes'} placeholderTextColor={colors.textMuted} style={[styles.input,styles.notes]}/><View style={styles.dialogActions}><Pressable onPress={close}><Text style={styles.cancel}>Cancel</Text></Pressable><Pressable disabled={process.isPending||reject.isPending||(action==='process'&&!finalNo.trim())} onPress={()=>action==='process'?process.mutate():reject.mutate()} style={[action==='process'?styles.processConfirm:styles.rejectConfirm,(process.isPending||reject.isPending)&&styles.disabled]}>{process.isPending||reject.isPending?<ActivityIndicator color="#fff"/>:<Text style={styles.confirmText}>Confirm</Text>}</Pressable></View></View></View></Modal>
 </Screen>;
}
function Mini({label,value}:{label:string;value:string}){return <View style={styles.mini}><Text style={styles.miniLabel}>{label}</Text><Text numberOfLines={1} style={styles.miniValue}>{value}</Text></View>}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},error:{color:colors.danger},list:{gap:spacing.sm,paddingBottom:spacing.xxl},header:{gap:spacing.sm,marginBottom:spacing.md},search:{minHeight:48,flexDirection:'row',alignItems:'center',gap:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:spacing.md,backgroundColor:'#fff'},searchInput:{flex:1,minHeight:46,color:colors.text},input:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:spacing.md,backgroundColor:'#fff',color:colors.text},message:{color:colors.navy,fontSize:11,fontWeight:'700'},card:{gap:spacing.md,padding:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.surface},pressed:{opacity:.8},top:{flexDirection:'row',justifyContent:'space-between',gap:spacing.sm},copy:{flex:1},no:{color:colors.text,fontSize:14,fontWeight:'900'},customer:{color:colors.textMuted,fontSize:11,marginTop:2},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},mini:{width:'47%'},miniLabel:{color:colors.textMuted,fontSize:9,fontWeight:'700'},miniValue:{color:colors.text,fontSize:11,fontWeight:'800',marginTop:2},actions:{flexDirection:'row',gap:spacing.sm},process:{flex:1,minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.navy},processText:{color:'#fff',fontSize:11,fontWeight:'900'},reject:{minWidth:92,minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:radius.md,borderWidth:1,borderColor:colors.danger},rejectText:{color:colors.danger,fontSize:11,fontWeight:'900'},modalBackdrop:{flex:1,justifyContent:'center',backgroundColor:'rgba(2,6,23,.65)'},dialog:{margin:spacing.xl,padding:spacing.xl,gap:spacing.md,borderRadius:radius.xl,backgroundColor:colors.surface},dialogTitle:{color:colors.text,fontSize:18,fontWeight:'900'},dialogText:{color:colors.textMuted,fontSize:12},label:{color:colors.textMuted,fontSize:9,fontWeight:'900',textTransform:'uppercase'},notes:{minHeight:90,textAlignVertical:'top',paddingTop:spacing.md},dialogActions:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:spacing.lg},cancel:{color:colors.textMuted,fontWeight:'800'},processConfirm:{minHeight:44,minWidth:92,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.navy},rejectConfirm:{minHeight:44,minWidth:92,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.danger},confirmText:{color:'#fff',fontWeight:'900'},disabled:{opacity:.45}});
