import { useMemo, useState } from 'react';
import { router } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { formatCreditMoney } from '@/services/creditDispatch';
import { getCreditCustomerAging, getCreditCustomerOutstanding } from '@/services/creditCustomers';
import { colors, radius, spacing } from '@/theme/tokens';

export default function CreditCustomersScreen(){
 const [mode,setMode]=useState<'outstanding'|'aging'>('outstanding'); const [search,setSearch]=useState('');
 const outstanding=useQuery({queryKey:['credit-customers-outstanding'],queryFn:getCreditCustomerOutstanding}); const aging=useQuery({queryKey:['credit-customers-aging'],queryFn:getCreditCustomerAging});
 const needle=search.trim().toLowerCase(); const outstandingRows=useMemo(()=>(outstanding.data??[]).filter((r)=>!needle||`${r.customer_name} ${r.mobile_no} ${r.default_branch??''}`.toLowerCase().includes(needle)),[outstanding.data,needle]); const agingRows=useMemo(()=>(aging.data??[]).filter((r)=>!needle||`${r.customer_name} ${r.mobile_no} ${r.default_branch??''}`.toLowerCase().includes(needle)),[aging.data,needle]);
 const summary=useMemo(()=>({outstanding:(outstanding.data??[]).reduce((s,r)=>s+Number(r.outstanding||0),0),overdue:(outstanding.data??[]).reduce((s,r)=>s+Number(r.overdue||0),0),customers:(outstanding.data??[]).length}),[outstanding.data]);
 return <Screen title="Credit Customers" subtitle="Outstanding, aging and customer ledger">
   <Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable>
   <View style={styles.metrics}><Metric label="Customers" value={String(summary.customers)}/><Metric label="Outstanding" value={formatCreditMoney(summary.outstanding)}/><Metric label="Overdue" value={formatCreditMoney(summary.overdue)}/></View>
   <View style={styles.segment}><Pressable onPress={()=>setMode('outstanding')} style={[styles.segmentButton,mode==='outstanding'&&styles.segmentActive]}><Text style={[styles.segmentText,mode==='outstanding'&&styles.segmentTextActive]}>Outstanding</Text></Pressable><Pressable onPress={()=>setMode('aging')} style={[styles.segmentButton,mode==='aging'&&styles.segmentActive]}><Text style={[styles.segmentText,mode==='aging'&&styles.segmentTextActive]}>Aging</Text></Pressable></View>
   <TextInput value={search} onChangeText={setSearch} placeholder="Customer, mobile or branch" placeholderTextColor={colors.textMuted} style={styles.input}/>
   {mode==='outstanding'?outstandingRows.map((row)=><Pressable key={row.customer_id} onPress={()=>router.push(`/credit-dispatch/customer/${row.customer_id}`)} style={({pressed})=>[styles.card,pressed&&styles.pressed]}><View style={styles.top}><View style={styles.copy}><Text style={styles.name}>{row.customer_name}</Text><Text style={styles.meta}>{row.mobile_no} • {row.default_branch||'—'}</Text></View><Risk risk={row.risk_category}/></View><View style={styles.grid}><Mini label="Credit" value={formatCreditMoney(row.total_credit)}/><Mini label="Received" value={formatCreditMoney(row.total_received)}/><Mini label="Outstanding" value={formatCreditMoney(row.outstanding)}/><Mini label="Overdue" value={formatCreditMoney(row.overdue)}/></View></Pressable>):agingRows.map((row)=><Pressable key={row.customer_id} onPress={()=>router.push(`/credit-dispatch/customer/${row.customer_id}`)} style={({pressed})=>[styles.card,pressed&&styles.pressed]}><View style={styles.top}><View style={styles.copy}><Text style={styles.name}>{row.customer_name}</Text><Text style={styles.meta}>{row.mobile_no} • {row.default_branch||'—'}</Text></View><Risk risk={row.risk_category}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.aging}><Age label="0–7" value={row.bucket_0_7}/><Age label="8–15" value={row.bucket_8_15}/><Age label="16–30" value={row.bucket_16_30}/><Age label="30+" value={row.bucket_30_plus}/><Age label="Overdue" value={row.overdue}/></ScrollView></Pressable>)}
   {((mode==='outstanding'&&!outstanding.isLoading&&!outstandingRows.length)||(mode==='aging'&&!aging.isLoading&&!agingRows.length))?<Text style={styles.empty}>No customers found.</Text>:null}
 </Screen>
}
function Metric({label,value}:{label:string;value:string}){return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text numberOfLines={1} style={styles.metricValue}>{value}</Text></View>}
function Risk({risk}:{risk:string}){const tone=risk==='Red'?{bg:colors.dangerSoft,fg:colors.danger}:risk==='Amber'?{bg:colors.warningSoft,fg:colors.warning}:{bg:colors.successSoft,fg:colors.success};return <View style={[styles.risk,{backgroundColor:tone.bg}]}><Text style={[styles.riskText,{color:tone.fg}]}>{risk}</Text></View>}
function Mini({label,value}:{label:string;value:string}){return <View style={styles.mini}><Text style={styles.miniLabel}>{label}</Text><Text numberOfLines={1} style={styles.miniValue}>{value}</Text></View>}
function Age({label,value}:{label:string;value:number}){return <View style={styles.age}><Text style={styles.ageLabel}>{label}</Text><Text style={styles.ageValue}>{formatCreditMoney(value)}</Text></View>}
const styles=StyleSheet.create({back:{color:colors.blue,fontSize:13,fontWeight:'900'},metrics:{flexDirection:'row',gap:spacing.sm},metric:{flex:1,padding:spacing.md,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},metricLabel:{color:colors.textMuted,fontSize:9,fontWeight:'700'},metricValue:{color:colors.text,fontSize:14,fontWeight:'900',marginTop:2},segment:{flexDirection:'row',gap:4,padding:4,borderRadius:radius.md,backgroundColor:colors.surfaceMuted},segmentButton:{flex:1,minHeight:40,alignItems:'center',justifyContent:'center',borderRadius:radius.sm},segmentActive:{backgroundColor:colors.navy},segmentText:{color:colors.textMuted,fontSize:11,fontWeight:'900'},segmentTextActive:{color:'#fff'},input:{minHeight:48,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,paddingHorizontal:spacing.md,color:colors.text,fontSize:13},card:{padding:spacing.md,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,gap:spacing.md},pressed:{opacity:.8},top:{flexDirection:'row',justifyContent:'space-between',gap:spacing.sm},copy:{flex:1},name:{color:colors.text,fontSize:13,fontWeight:'900'},meta:{color:colors.textMuted,fontSize:10,marginTop:2},risk:{paddingHorizontal:8,paddingVertical:5,borderRadius:radius.sm},riskText:{fontSize:9,fontWeight:'900'},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},mini:{width:'47%'},miniLabel:{color:colors.textMuted,fontSize:9,fontWeight:'700'},miniValue:{color:colors.text,fontSize:11,fontWeight:'900',marginTop:2},aging:{gap:spacing.sm},age:{minWidth:92,padding:spacing.sm,borderRadius:radius.md,backgroundColor:colors.surfaceMuted},ageLabel:{color:colors.textMuted,fontSize:9,fontWeight:'700'},ageValue:{color:colors.text,fontSize:11,fontWeight:'900',marginTop:2},empty:{color:colors.textMuted,textAlign:'center',padding:spacing.xl}});
