import { getInstallationDocumentUrl, type InstallationEntry } from '../../services/installations.service';

const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char] ?? char));
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }) : '-';
const label = (value: string) => value.replace(/_/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());

export async function downloadInstallationReport(entry: InstallationEntry) {
  const popup = window.open('', '_blank', 'width=1000,height=760');
  if (!popup) throw new Error('Allow pop-ups to generate the installation report.');
  popup.document.write('<!doctype html><html><body style="font-family:Arial;padding:24px;color:#334155">Preparing installation report…</body></html>');
  popup.document.close();
  try {
    const docs = (entry.portal_installation_documents ?? []).filter((doc) => doc.is_active);
    const documentRows = await Promise.all(docs.map(async (doc) => ({ ...doc, url: await getInstallationDocumentUrl(doc.storage_path) })));
    const items = (entry.portal_installation_items ?? []).map((item, index) => `<tr><td>${index + 1}</td><td>${escapeHtml(item.part_no)}</td><td>${escapeHtml(item.description)}</td><td class="num">${escapeHtml(item.quantity)}</td></tr>`).join('');
    const documents = documentRows.map((doc) => `<tr><td>${escapeHtml(label(doc.document_type))}</td><td>${escapeHtml(doc.file_name)}</td><td>${escapeHtml((doc.file_size / 1024 / 1024).toFixed(2))} MB</td><td><a href="${escapeHtml(doc.url)}" target="_blank" rel="noreferrer">Open document</a></td></tr>`).join('');
    const statusLabel = entry.status === 'ACCEPTANCE_PENDING' ? 'Acceptance Pending' : label(entry.status);

    popup.document.open();
    popup.document.write(`<!doctype html><html><head><title>${escapeHtml(entry.entry_no)} Installation Report</title><meta charset="utf-8"/><style>
      *{box-sizing:border-box}body{margin:0;background:#eef2f7;color:#172033;font-family:Arial,Helvetica,sans-serif}.toolbar{position:sticky;top:0;display:flex;justify-content:flex-end;gap:10px;padding:12px 20px;background:#0b1f3a}.toolbar button{border:0;border-radius:6px;padding:9px 16px;font-weight:700;cursor:pointer}.primary{background:#f5c400;color:#172033}.secondary{background:white;color:#172033}.sheet{width:210mm;min-height:297mm;margin:18px auto;background:white;padding:16mm;box-shadow:0 8px 28px rgba(15,23,42,.18)}.header{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #0f5fa8;padding-bottom:12px}.brand h1{margin:0;color:#0b1f3a;font-size:24px}.brand p{margin:5px 0 0;color:#526071;font-size:12px}.status{align-self:flex-start;border:1px solid #8fb7d8;background:#eef7ff;color:#0b4d8a;border-radius:999px;padding:7px 12px;font-size:12px;font-weight:700}.section{margin-top:18px}.section-title{margin:0 0 8px;padding:8px 10px;background:#eaf0f6;color:#0b1f3a;font-size:12px;text-transform:uppercase;letter-spacing:.08em}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.field{border:1px solid #d7e0ea;border-radius:6px;padding:9px}.field small{display:block;color:#667085;text-transform:uppercase;font-size:9px;font-weight:700;letter-spacing:.06em}.field strong{display:block;margin-top:5px;font-size:12px;word-break:break-word}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #d7e0ea;padding:8px;text-align:left;vertical-align:top}th{background:#f3f6f9;color:#334155;text-transform:uppercase;font-size:9px}.num{text-align:right}.footer{margin-top:24px;padding-top:10px;border-top:1px solid #cbd5e1;color:#667085;font-size:9px;display:flex;justify-content:space-between}a{color:#075fb8;font-weight:700}@media print{body{background:white}.toolbar{display:none}.sheet{margin:0;box-shadow:none;width:auto;min-height:auto;padding:12mm}@page{size:A4;margin:0}}
    </style></head><body><div class="toolbar"><button class="secondary" onclick="window.close()">Close</button><button class="primary" onclick="window.print()">Save as PDF / Print</button></div><main class="sheet"><header class="header"><div class="brand"><h1>Installation Documentation Report</h1><p>Parts Connect Portal • Engine / Rock Breaker Installation Record</p></div><div class="status">${escapeHtml(statusLabel)}</div></header>
    <section class="section"><h2 class="section-title">Entry Information</h2><div class="grid"><div class="field"><small>Entry No.</small><strong>${escapeHtml(entry.entry_no)}</strong></div><div class="field"><small>Equipment Type</small><strong>${escapeHtml(label(entry.equipment_type))}</strong></div><div class="field"><small>Invoice Date</small><strong>${escapeHtml(formatDate(entry.invoice_date))}</strong></div><div class="field"><small>Branch</small><strong>${escapeHtml(entry.branch)}</strong></div><div class="field"><small>Customer Name</small><strong>${escapeHtml(entry.customer_name)}</strong></div><div class="field"><small>DBMS Invoice No.</small><strong>${escapeHtml(entry.invoice_no)}</strong></div></div></section>
    <section class="section"><h2 class="section-title">Installation References</h2><div class="grid"><div class="field"><small>JCB Invoice No.</small><strong>${escapeHtml(entry.jcb_invoice_no || '-')}</strong></div><div class="field"><small>SVR No.</small><strong>${escapeHtml(entry.svr_no || '-')}</strong></div><div class="field"><small>Equipment Registration No.</small><strong>${escapeHtml(entry.equipment_registration_no || 'Pending')}</strong></div><div class="field"><small>Branch Submitted On</small><strong>${escapeHtml(formatDate(entry.branch_submitted_at))}</strong></div><div class="field"><small>Accepted On</small><strong>${escapeHtml(formatDate(entry.accepted_at))}</strong></div><div class="field"><small>Current Status</small><strong>${escapeHtml(statusLabel)}</strong></div></div></section>
    <section class="section"><h2 class="section-title">Part Details</h2><table><thead><tr><th>#</th><th>Part No.</th><th>Description</th><th class="num">Quantity</th></tr></thead><tbody>${items || '<tr><td colspan="4">No part details available.</td></tr>'}</tbody></table></section>
    <section class="section"><h2 class="section-title">Uploaded Documents</h2><table><thead><tr><th>Document</th><th>File Name</th><th>Size</th><th>Secure Preview</th></tr></thead><tbody>${documents || '<tr><td colspan="4">No documents uploaded.</td></tr>'}</tbody></table></section>
    <footer class="footer"><span>Generated from Parts Connect Portal</span><span>Generated on ${escapeHtml(new Date().toLocaleString('en-IN'))}</span></footer></main></body></html>`);
    popup.document.close();
  } catch (error) {
    popup.close();
    throw error;
  }
}
