import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { Download, Eye, FileText, FileUp, ShieldCheck } from 'lucide-react';
import { useAuth } from '../../auth/useAuth';
import { PageCard } from '../../components/ui/PageCard';
import { ConfirmDialog } from '../../components/ui/ConfirmDialog';
import { acceptInstallationEntry, getInstallationDocumentUrl, getInstallationEntry, INSTALLATION_VIEWER_PROFILE_ID, submitInstallationEntry, uploadInstallationDocument, type InstallationDocumentType } from '../../services/installations.service';
import { downloadInstallationReport } from './installationReport';

const normalizeBranch = (value?: string | null) => String(value ?? '').trim().toUpperCase().replace(/\s+/g,'_');
const statusLabel = (status:string) => status === 'ACCEPTANCE_PENDING' ? 'Acceptance Pending' : status.charAt(0)+status.slice(1).toLowerCase();
function sizeLabel(value:number) { return value >= 1024*1024 ? `${(value/1024/1024).toFixed(1)} MB` : `${Math.round(value/1024)} KB`; }

export function InstallationDetailPage() {
  const { installationId = '' } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const { profile, session } = useAuth();
  const query = useQuery({ queryKey:['installation-entry',installationId], queryFn:()=>getInstallationEntry(installationId), enabled:Boolean(installationId) });
  const entry = query.data; const [jcbNo,setJcbNo] = useState(''); const [svrNo,setSvrNo] = useState(''); const [registrationNo,setRegistrationNo] = useState(''); const [message,setMessage] = useState(''); const [uploading,setUploading] = useState<string>(''); const [confirmAction,setConfirmAction] = useState<'submit'|'accept'|null>(null); const [reportBusy,setReportBusy] = useState(false);
  const assignedBranch = Boolean(entry && normalizeBranch(profile?.branch) === normalizeBranch(entry.branch));
  const isServiceCrm = profile?.id === INSTALLATION_VIEWER_PROFILE_ID || session?.user?.id === INSTALLATION_VIEWER_PROFILE_ID;
  const docs = (entry?.portal_installation_documents ?? []).filter((doc)=>doc.is_active);
  async function refresh() { await queryClient.invalidateQueries({ queryKey:['installation-entry',installationId] }); await queryClient.invalidateQueries({ queryKey:['installation-entries'] }); await queryClient.invalidateQueries({queryKey:['installation-pending-count']}); await query.refetch(); }
  async function handleUpload(type:InstallationDocumentType,file?:File) { if (!file) return; try { setUploading(type); setMessage(''); await uploadInstallationDocument(installationId,type,file); await refresh(); setMessage(`${type.replace(/_/g,' ')} uploaded successfully.`); } catch(e) { setMessage(e instanceof Error?e.message:'Upload failed.'); } finally { setUploading(''); } }
  async function openDocument(path:string,download=false) { const url = await getInstallationDocumentUrl(path); if (download) { const link=document.createElement('a'); link.href=url; link.download=''; link.target='_blank'; link.click(); } else window.open(url,'_blank','noopener,noreferrer'); }
  async function handleReport(){if(!entry)return;try{setReportBusy(true);setMessage('');await downloadInstallationReport(entry);}catch(e){setMessage(e instanceof Error?e.message:'Could not generate report.');}finally{setReportBusy(false);}}
  const submitMutation = useMutation({ mutationFn:()=>submitInstallationEntry(installationId,jcbNo,svrNo), onSuccess:async()=>{setConfirmAction(null);setMessage('Entry submitted and marked Acceptance Pending.'); await refresh();}, onError:(e)=>{setConfirmAction(null);setMessage(e instanceof Error?e.message:'Could not submit entry.');} });
  const acceptMutation = useMutation({ mutationFn:()=>acceptInstallationEntry(installationId,registrationNo), onSuccess:async()=>{setConfirmAction(null);setMessage('Entry accepted successfully.'); await refresh();}, onError:(e)=>{setConfirmAction(null);setMessage(e instanceof Error?e.message:'Could not accept entry.');} });
  if (query.isLoading) return <PageCard eyebrow="Installation Management" title="Loading entry…" description=""/>;
  if (!entry || query.error) return <PageCard eyebrow="Installation Management" title="Installation Entry" description=""><p className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">Could not load this installation entry.</p></PageCard>;
  const isAcceptanceStage = entry.status === 'ACCEPTANCE_PENDING' || entry.status === 'ACCEPTED';
  return <PageCard eyebrow="Installation Management" title={entry.entry_no} description={`${entry.equipment_type==='ROCK_BREAKER'?'Rock Breaker':'Engine'} • ${statusLabel(entry.status)}`}>
    {isAcceptanceStage?<div className="rounded-xl border border-[#9fc4e6] bg-gradient-to-r from-[#eef7ff] to-white p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-[#0b1f3a] text-white"><ShieldCheck className="h-5 w-5"/></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#0f5fa8]">Official Installation File</p><h2 className="mt-1 text-lg font-semibold text-[#0b1f3a]">{statusLabel(entry.status)}</h2><p className="mt-1 text-xs text-[#526071]">Review the complete documentation and download a formal report for the official file.</p></div></div><button onClick={handleReport} disabled={reportBusy} className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-[#0f5fa8] px-4 text-xs font-semibold text-white disabled:bg-[#dbe7f1] disabled:text-[#64748b]"><FileText className="h-4 w-4"/>{reportBusy?'Preparing…':'Download Report'}</button></div></div>:null}
    <section className="mt-3 rounded-xl border border-[#d8e0ea] bg-white"><div className="border-b bg-[#eaf0f6] px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#334155]">Entry Information</div><div className="grid gap-4 p-4 md:grid-cols-3"><Info label="Invoice Date" value={new Date(entry.invoice_date).toLocaleDateString('en-IN')}/><Info label="Branch" value={entry.branch}/><Info label="Customer Name" value={entry.customer_name}/><Info label="DBMS Invoice No." value={entry.invoice_no}/><Info label="Equipment Type" value={entry.equipment_type==='ROCK_BREAKER'?'Rock Breaker':'Engine'}/><Info label="Status" value={statusLabel(entry.status)}/></div></section>
    <section className="mt-3 rounded-xl border border-[#d8e0ea] bg-white"><div className="border-b bg-[#eaf0f6] px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#334155]">Installation References</div><div className="grid gap-4 p-4 md:grid-cols-3"><Info label="JCB Invoice No." value={entry.jcb_invoice_no || (entry.status==='PENDING'?'Pending':'-')}/><Info label="DBMS Invoice No." value={entry.invoice_no}/><Info label="SVR No." value={entry.svr_no || (entry.status==='PENDING'?'Pending':'-')}/><Info label="Equipment Registration No." value={entry.equipment_registration_no || 'Pending'}/><Info label="Branch Submitted On" value={entry.branch_submitted_at ? new Date(entry.branch_submitted_at).toLocaleString('en-IN') : '-'}/><Info label="Accepted On" value={entry.accepted_at ? new Date(entry.accepted_at).toLocaleString('en-IN') : '-'}/></div></section>
    <div className="mt-3 overflow-hidden rounded-xl border border-[#d8e0ea] bg-white"><div className="bg-[#eaf0f6] px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#334155]">Part Details</div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b text-left text-[10px] uppercase text-[#64748b]"><th className="px-3 py-2">Part No.</th><th className="px-3 py-2">Description</th><th className="w-28 px-3 py-2 text-right">Quantity</th></tr></thead><tbody>{(entry.portal_installation_items??[]).map((item)=><tr key={item.id} className="border-b last:border-0"><td className="px-3 py-2 font-semibold text-[#075fb8]">{item.part_no}</td><td className="px-3 py-2">{item.description}</td><td className="px-3 py-2 text-right font-semibold">{item.quantity}</td></tr>)}</tbody></table></div></div>
    <section className="mt-3"><div className="mb-2 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#334155]">Uploaded Documents</div><div className="grid gap-3 lg:grid-cols-3">{(['JCB_INVOICE','DBMS_INVOICE','SVR'] as InstallationDocumentType[]).map((type)=>{ const doc=docs.find((d)=>d.document_type===type); return <div key={type} className="rounded-xl border border-[#d8e0ea] bg-white p-3 shadow-sm"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-md bg-[#eef7ff] text-[#0f5fa8]"><FileText className="h-4 w-4"/></div><div><p className="text-[10px] font-semibold uppercase text-[#64748b]">{type.replace(/_/g,' ')}</p><p className="text-xs font-semibold text-[#0f172a]">{type==='JCB_INVOICE'?(entry.jcb_invoice_no||'Pending'):type==='DBMS_INVOICE'?entry.invoice_no:(entry.svr_no||'Pending')}</p></div></div>{doc?<div className="mt-3 rounded-lg border bg-[#f8fafc] p-3"><p className="truncate text-xs font-semibold">{doc.file_name}</p><p className="mt-1 text-[10px] text-[#64748b]">{sizeLabel(doc.file_size)} • Uploaded {new Date(doc.uploaded_at).toLocaleDateString('en-IN')}</p><div className="mt-3 flex gap-2"><button onClick={()=>openDocument(doc.storage_path)} className="inline-flex h-8 items-center gap-1 rounded-md border bg-white px-2 text-[11px] text-[#334155]"><Eye className="h-3.5 w-3.5"/>Preview</button><button onClick={()=>openDocument(doc.storage_path,true)} className="inline-flex h-8 items-center gap-1 rounded-md border bg-white px-2 text-[11px] text-[#334155]"><Download className="h-3.5 w-3.5"/>Download</button></div></div>:<p className="mt-3 rounded-md bg-amber-50 px-3 py-2 text-xs text-amber-800">Not uploaded</p>}{entry.status==='PENDING'&&assignedBranch?<label className={`mt-3 inline-flex h-9 cursor-pointer items-center gap-2 rounded-md border px-3 text-xs font-semibold ${uploading ? 'border-[#b9cee2] bg-[#eaf3fb] text-[#334155]' : 'border-[#0f5fa8] bg-[#0f5fa8] text-white hover:bg-[#0b4d8a]'}`}><FileUp className="h-4 w-4"/>{uploading===type?'Uploading…':doc?'Replace File':'Upload File'}<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="hidden" disabled={Boolean(uploading)} onChange={(e)=>handleUpload(type,e.target.files?.[0])}/></label>:null}</div>;})}</div></section>
    {entry.status==='PENDING'&&assignedBranch?<div className="mt-3 rounded-xl border border-[#d8e0ea] bg-white p-4"><h3 className="text-sm font-semibold">Branch Completion</h3><p className="mt-1 text-xs text-[#64748b]">All users assigned to {entry.branch} may upload and complete this entry.</p><div className="mt-3 grid gap-3 md:grid-cols-3"><label className="text-xs font-semibold">JCB Invoice No.<input value={jcbNo} onChange={(e)=>setJcbNo(e.target.value.toUpperCase())} className="mt-1 h-10 w-full rounded-md border px-3 uppercase"/></label><label className="text-xs font-semibold">DBMS Invoice No.<input value={entry.invoice_no} readOnly className="mt-1 h-10 w-full rounded-md border bg-[#f1f5f9] px-3"/></label><label className="text-xs font-semibold">SVR No.<input value={svrNo} onChange={(e)=>setSvrNo(e.target.value.toUpperCase())} className="mt-1 h-10 w-full rounded-md border px-3 uppercase"/></label></div><div className="mt-3 flex justify-end"><button disabled={!jcbNo.trim()||!svrNo.trim()||submitMutation.isPending} onClick={()=>setConfirmAction('submit')} className="h-9 rounded-md bg-[#0f5fa8] px-5 text-xs font-semibold text-white disabled:bg-[#dbe7f1] disabled:text-[#64748b] disabled:opacity-100">{submitMutation.isPending?'Submitting…':'Submit Documents'}</button></div></div>:null}
    {entry.status==='ACCEPTANCE_PENDING'&&isServiceCrm?<div className="mt-3 rounded-xl border border-[#b9d5ef] bg-[#eef7ff] p-4"><h3 className="text-sm font-semibold text-[#0b4d8a]">Service CRM Acceptance</h3><p className="mt-1 text-xs text-[#526071]">Review all invoice and SVR documents before recording the equipment registration number.</p><label className="mt-3 block max-w-md text-xs font-semibold">Equipment Registration No.<input value={registrationNo} onChange={(e)=>setRegistrationNo(e.target.value.toUpperCase())} className="mt-1 h-10 w-full rounded-md border border-[#9fc4e6] bg-white px-3 uppercase"/></label><button disabled={!registrationNo.trim()||acceptMutation.isPending} onClick={()=>setConfirmAction('accept')} className="mt-3 h-9 rounded-md bg-[#0b1f3a] px-5 text-xs font-semibold text-white disabled:bg-[#dbe7f1] disabled:text-[#64748b] disabled:opacity-100">{acceptMutation.isPending?'Accepting…':'Accept Entry'}</button></div>:null}
    {message?<p className="mt-3 rounded-md border border-[#b9d5ef] bg-[#eef7ff] p-3 text-sm text-[#0b4d8a]">{message}</p>:null}
    <div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>navigate('/installations')} className="h-9 rounded-md border border-[#cbd5e1] bg-white px-4 text-xs font-semibold text-[#334155]">Back to Installations</button>{isAcceptanceStage?<button onClick={handleReport} disabled={reportBusy} className="inline-flex h-9 items-center gap-2 rounded-md border border-[#0f5fa8] bg-white px-4 text-xs font-semibold text-[#0f5fa8]"><Download className="h-4 w-4"/>Download Report</button>:null}</div>
    <ConfirmDialog open={confirmAction==='submit'} title="Submit installation documents?" message="Mark this entry as Acceptance Pending and send it to Service CRM for equipment registration and final acceptance?" confirmLabel="Submit for Acceptance" busy={submitMutation.isPending} onCancel={()=>setConfirmAction(null)} onConfirm={()=>submitMutation.mutate()}/>
    <ConfirmDialog open={confirmAction==='accept'} title="Accept installation entry?" message={`Confirm equipment registration number ${registrationNo || '-'} and mark this entry as Accepted.`} confirmLabel="Accept Entry" tone="success" busy={acceptMutation.isPending} onCancel={()=>setConfirmAction(null)} onConfirm={()=>acceptMutation.mutate()}/>
  </PageCard>;
}
function Info({label,value}:{label:string;value:string}) { return <div><p className="text-[10px] font-semibold uppercase text-[#64748b]">{label}</p><p className="mt-1 text-sm font-semibold text-[#0f172a]">{value}</p></div>; }
