import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Check, Plus, Trash2 } from 'lucide-react';
import { PageCard } from '../../components/ui/PageCard';
import { createInstallationEntry, listInstallationBranches, type EquipmentType, type InstallationItem } from '../../services/installations.service';

const today = new Date().toISOString().slice(0,10);
export function NewInstallationPage() {
  const navigate = useNavigate(); const [equipmentType,setEquipmentType] = useState<EquipmentType>('ENGINE');
  const [invoiceDate,setInvoiceDate] = useState(today); const [branch,setBranch] = useState(''); const [invoiceNo,setInvoiceNo] = useState(''); const [customerName,setCustomerName] = useState('');
  const [items,setItems] = useState<InstallationItem[]>([{ part_no:'', description:'', quantity:1 }]); const [error,setError] = useState('');
  const branches = useQuery({ queryKey:['installation-branches'], queryFn:listInstallationBranches });
  const mutation = useMutation({ mutationFn: createInstallationEntry, onSuccess:(id) => navigate(`/installations/${id}`, { replace:true }), onError:(e) => setError(e instanceof Error ? e.message : 'Could not create entry.') });
  function patchText(index:number,key:'part_no'|'description',value:string) { setItems((current) => current.map((item,i) => i===index ? {...item,[key]:value} : item)); }
  function patchQuantity(index:number,value:number) { setItems((current) => current.map((item,i) => i===index ? {...item,quantity:value} : item)); }
  function submit() {
    setError('');
    if (!invoiceDate || !branch || !invoiceNo.trim() || !customerName.trim() || items.some((i) => !i.part_no.trim() || !i.description.trim() || Number(i.quantity)<=0)) { setError('Complete all required fields and item details.'); return; }
    if (!window.confirm(`Create this ${equipmentType === 'ENGINE' ? 'Engine' : 'Rock Breaker'} entry for ${branch}?`)) return;
    mutation.mutate({ equipment_type:equipmentType, invoice_date:invoiceDate, branch, invoice_no:invoiceNo.trim(), customer_name:customerName.trim(), items });
  }
  return <PageCard eyebrow="Installation Management" title="Add New Installation Entry" description="Create the branch task and invoice item details">
    <div className="flex justify-end"><div className="inline-flex rounded-lg border border-[#cbd5e1] bg-[#f8fafc] p-1">{(['ENGINE','ROCK_BREAKER'] as EquipmentType[]).map((type) => <button key={type} onClick={() => setEquipmentType(type)} className={`inline-flex h-9 items-center gap-2 rounded-md px-4 text-xs font-semibold ${equipmentType===type ? 'bg-[#0b1f3a] text-white shadow' : 'text-[#334155]'}`}>{equipmentType===type ? <Check className="h-4 w-4"/> : null}{type==='ENGINE'?'Engine':'Rock Breaker'}</button>)}</div></div>
    <div className="mt-3 grid gap-3 rounded-xl border border-[#d8e0ea] bg-white p-4 md:grid-cols-2"><label className="text-xs font-semibold text-[#334155]">Invoice Date<input type="date" value={invoiceDate} onChange={(e)=>setInvoiceDate(e.target.value)} className="mt-1 h-10 w-full rounded-md border border-[#cbd5e1] px-3 text-sm"/></label><label className="text-xs font-semibold text-[#334155]">Branch<select value={branch} onChange={(e)=>setBranch(e.target.value)} className="mt-1 h-10 w-full rounded-md border border-[#cbd5e1] bg-white px-3 text-sm"><option value="">Select branch</option>{(branches.data??[]).map((name)=><option key={name}>{name}</option>)}</select></label><label className="text-xs font-semibold text-[#334155]">Invoice No.<input value={invoiceNo} onChange={(e)=>setInvoiceNo(e.target.value.toUpperCase())} className="mt-1 h-10 w-full rounded-md border border-[#cbd5e1] px-3 text-sm uppercase"/></label><label className="text-xs font-semibold text-[#334155]">Customer Name<input value={customerName} onChange={(e)=>setCustomerName(e.target.value)} className="mt-1 h-10 w-full rounded-md border border-[#cbd5e1] px-3 text-sm"/></label></div>
    <div className="mt-3 overflow-hidden rounded-xl border border-[#d8e0ea] bg-white"><div className="flex items-center justify-between bg-[#eaf0f6] px-3 py-2"><h3 className="text-xs font-semibold uppercase text-[#334155]">Parts</h3><button onClick={()=>setItems((v)=>[...v,{part_no:'',description:'',quantity:1}])} className="inline-flex h-8 items-center gap-1 rounded-md bg-[#0f5fa8] px-3 text-[11px] font-semibold text-white"><Plus className="h-3.5 w-3.5"/>Add Part</button></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-xs"><thead><tr className="border-b text-left text-[10px] uppercase text-[#64748b]"><th className="px-3 py-2">Part No.</th><th className="px-3 py-2">Description</th><th className="w-28 px-3 py-2">Quantity</th><th className="w-16 px-3 py-2"></th></tr></thead><tbody>{items.map((item,index)=><tr key={index} className="border-b last:border-0"><td className="px-3 py-2"><input value={item.part_no} onChange={(e)=>patchText(index,'part_no',e.target.value.toUpperCase())} className="h-9 w-full rounded-md border px-2 uppercase"/></td><td className="px-3 py-2"><input value={item.description} onChange={(e)=>patchText(index,'description',e.target.value)} className="h-9 w-full rounded-md border px-2"/></td><td className="px-3 py-2"><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={(e)=>patchQuantity(index,Number(e.target.value))} className="h-9 w-full rounded-md border px-2"/></td><td className="px-3 py-2"><button disabled={items.length===1} onClick={()=>setItems((v)=>v.filter((_,i)=>i!==index))} className="grid h-8 w-8 place-items-center rounded-md border text-red-600 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div></div>
    {error ? <p className="mt-3 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}
    <div className="mt-3 flex justify-end gap-2"><button onClick={()=>navigate('/installations')} className="h-9 rounded-md border border-[#cbd5e1] px-4 text-xs font-semibold">Cancel</button><button disabled={mutation.isPending} onClick={submit} className="h-9 rounded-md bg-[#0f5fa8] px-5 text-xs font-semibold text-white disabled:opacity-50">{mutation.isPending?'Creating…':'Create Entry'}</button></div>
  </PageCard>;
}
