import { useState } from 'react';
import { Linking, Pressable, StyleSheet, Text, TextInput, View, ActivityIndicator } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Screen } from '@/components/Screen';
import { StatusChip } from '@/components/StatusChip';
import { addOrderComment, getOrderActivity, getOrderAttachmentUrl } from '@/services/orderActivity';
import { colors, radius, spacing } from '@/theme/tokens';

export default function OrderActivityScreen(){
 const params=useLocalSearchParams<{orderId:string}>(); const orderId=Array.isArray(params.orderId)?params.orderId[0]:params.orderId; const qc=useQueryClient(); const query=useQuery({queryKey:['order-activity',orderId],queryFn:()=>getOrderActivity(orderId),enabled:Boolean(orderId)}); const [comment,setComment]=useState(''),[message,setMessage]=useState('');
 const add=useMutation({mutationFn:()=>addOrderComment(orderId,comment),onSuccess:async()=>{setComment('');setMessage('Comment added.');await query.refetch();await qc.invalidateQueries({queryKey:['order',orderId]})},onError:(e)=>setMessage(e instanceof Error?e.message:'Could not add comment.')});
 async function openAttachment(id:string){try{const link=await getOrderAttachmentUrl(id);await Linking.openURL(link.signedUrl)}catch(e){setMessage(e instanceof Error?e.message:'Could not open attachment.')}}
 return <Screen title="Order Activity" subtitle="Audit events, comments and billing movement">
  <Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable>
  <View style={styles.commentRow}><TextInput multiline value={comment} onChangeText={setComment} placeholder="Add order comment…" placeholderTextColor={colors.textMuted} style={styles.commentInput}/><Pressable disabled={!comment.trim()||add.isPending} onPress={()=>add.mutate()} style={[styles.addButton,(!comment.trim()||add.isPending)&&styles.disabled]}>{add.isPending?<ActivityIndicator color="#fff"/>:<Text style={styles.addText}>Add</Text>}</Pressable></View>{message?<Text style={styles.message}>{message}</Text>:null}
  {query.isLoading?<ActivityIndicator color={colors.navy}/>:null}
  <Text style={styles.section}>Events</Text>{(query.data?.events??[]).map((event)=><View key={event.id} style={styles.card}><View style={styles.top}><Text style={styles.eventType}>{event.event_type.replace(/_/g,' ')}</Text>{event.new_status?<StatusChip status={event.new_status}/>:null}</View>{event.notes?<Text style={styles.body}>{event.notes}</Text>:null}<Text style={styles.meta}>{new Date(event.created_at).toLocaleString('en-IN')}{event.old_status?` • ${event.old_status} → ${event.new_status||'—'}`:''}</Text></View>)}
  <Text style={styles.section}>Comments</Text>{(query.data?.comments??[]).map((commentRow)=><View key={commentRow.id} style={styles.card}><Text style={styles.body}>{commentRow.body||'—'}</Text><Text style={styles.meta}>{commentRow.author?.full_name||'System'}{commentRow.author?.role?` • ${commentRow.author.role}`:''} • {new Date(commentRow.created_at).toLocaleString('en-IN')}</Text>{commentRow.attachments.map((a)=><Pressable key={a.id} onPress={()=>void openAttachment(a.id)} style={styles.attachment}><Text style={styles.attachmentText}>📎 {a.original_file_name}</Text><Text style={styles.attachmentMeta}>{Math.round(Number(a.file_size_bytes||0)/1024)} KB</Text></Pressable>)}</View>)}
  <Text style={styles.section}>Billing / dispatch chunks</Text>{(query.data?.billings??[]).map((chunk)=><View key={chunk.id} style={styles.card}><View style={styles.top}><Text style={styles.eventType}>{chunk.part_no}</Text><StatusChip status={chunk.raw_status||'Billing'}/></View><View style={styles.grid}><Mini label="Billed" value={String(Number(chunk.billed_qty??0))}/><Mini label="Received" value={String(Number(chunk.received_qty??0))}/><Mini label="Invoice" value={chunk.invoice_no||'—'}/><Mini label="Docket" value={chunk.docket_no||'—'}/><Mini label="Transport" value={chunk.transport_name||'—'}/><Mini label="Received at" value={chunk.received_at?new Date(chunk.received_at).toLocaleDateString('en-IN'):'—'}/></View></View>)}
  {!query.isLoading&&!query.isError&&!query.data?.events.length&&!query.data?.comments.length&&!query.data?.billings.length?<Text style={styles.empty}>No activity recorded yet.</Text>:null}
 </Screen>
}
function Mini({label,value}:{label:string;value:string}){return <View style={styles.mini}><Text style={styles.miniLabel}>{label}</Text><Text numberOfLines={1} style={styles.miniValue}>{value}</Text></View>}
const styles=StyleSheet.create({back:{color:colors.blue,fontSize:13,fontWeight:'900'},commentRow:{flexDirection:'row',gap:spacing.sm},commentInput:{flex:1,minHeight:60,maxHeight:120,padding:spacing.md,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,color:colors.text,textAlignVertical:'top'},addButton:{width:64,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.navy},addText:{color:'#fff',fontSize:11,fontWeight:'900'},disabled:{opacity:.45},message:{color:colors.navy,fontSize:11,fontWeight:'700'},section:{color:colors.text,fontSize:14,fontWeight:'900',marginTop:spacing.xs},card:{padding:spacing.md,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,gap:spacing.sm},top:{flexDirection:'row',justifyContent:'space-between',gap:spacing.sm},eventType:{flex:1,color:colors.text,fontSize:12,fontWeight:'900',textTransform:'capitalize'},body:{color:colors.text,fontSize:11,lineHeight:17},meta:{color:colors.textMuted,fontSize:9,lineHeight:14},attachment:{minHeight:42,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.sm,paddingHorizontal:spacing.sm,borderRadius:radius.sm,backgroundColor:colors.surfaceMuted},attachmentText:{flex:1,color:colors.blue,fontSize:10,fontWeight:'800'},attachmentMeta:{color:colors.textMuted,fontSize:9},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},mini:{width:'47%'},miniLabel:{color:colors.textMuted,fontSize:9,fontWeight:'700'},miniValue:{color:colors.text,fontSize:10,fontWeight:'800',marginTop:2},empty:{color:colors.textMuted,textAlign:'center',padding:spacing.xl}});
