import { useMemo, useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { Screen } from '@/components/Screen';
import { addPartLocation, deactivatePartLocation, getKnownPartLocations, getPartLocationResult, type PartLocation } from '@/services/partLocation';
import { colors, radius, spacing } from '@/theme/tokens';

export default function ManagePartLocationScreen(){
  const {role}=useAuth(); const allowed=['manager','admin','developer'].includes(role??''); const qc=useQueryClient();
  const [partNo,setPartNo]=useState(''); const [part,setPart]=useState<Awaited<ReturnType<typeof getPartLocationResult>>['part']>(null); const [locations,setLocations]=useState<PartLocation[]>([]); const [location,setLocation]=useState(''); const [suggestions,setSuggestions]=useState<string[]>([]); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false); const [removeTarget,setRemoveTarget]=useState<PartLocation|null>(null);
  const normalized=useMemo(()=>partNo.trim().replace(/\s+/g,'').toUpperCase(),[partNo]);
  if(!allowed) return <View style={styles.center}><Text style={styles.error}>Only Manager, Admin and Developer can manage part locations.</Text></View>;
  async function lookup(){ if(!normalized)return; setLoading(true); setMessage(''); try{const result=await getPartLocationResult(normalized); setPart(result.part); setLocations(result.locations); if(!result.part)setMessage('Verify the Part No. first; this part is not in Part Master.');}catch(e){setMessage(e instanceof Error?e.message:'Lookup failed.');}finally{setLoading(false);} }
  async function suggest(value:string){setLocation(value); if(value.trim().length<2){setSuggestions([]);return;} try{setSuggestions(await getKnownPartLocations(value));}catch{setSuggestions([]);} }
  const addMutation=useMutation({mutationFn:()=>addPartLocation(normalized,location),onSuccess:async()=>{setLocation('');setSuggestions([]);setMessage('Location added.');await lookup();await qc.invalidateQueries({queryKey:['part-location']});},onError:e=>setMessage(e instanceof Error?e.message:'Could not add location.')});
  const removeMutation=useMutation({mutationFn:(id:string)=>deactivatePartLocation(id),onSuccess:async()=>{setRemoveTarget(null);setMessage('Location deactivated.');await lookup();},onError:e=>setMessage(e instanceof Error?e.message:'Could not deactivate location.')});
  return <Screen title="Manage Part Location" subtitle="Verify the part first, then maintain active physical locations.">
    <Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable>
    <View style={styles.searchRow}><TextInput autoCapitalize="characters" value={partNo} onChangeText={value=>{setPartNo(value);setPart(null);setLocations([]);}} placeholder="Part No." placeholderTextColor={colors.textMuted} style={styles.input}/><Pressable onPress={()=>void lookup()} disabled={loading} style={styles.primary}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Verify</Text>}</Pressable></View>
    {part?<View style={styles.verified}><Text style={styles.verifiedTitle}>{part.part_no}</Text><Text style={styles.verifiedText}>{part.description||'No description'}</Text></View>:null}
    {part?<View style={styles.form}><Text style={styles.sectionTitle}>Add location</Text><TextInput value={location} onChangeText={value=>void suggest(value)} placeholder="Rack / bin / shelf" placeholderTextColor={colors.textMuted} style={styles.input}/>{suggestions.slice(0,5).map(item=><Pressable key={item} onPress={()=>{setLocation(item);setSuggestions([]);}} style={styles.suggestion}><Text style={styles.suggestionText}>{item}</Text></Pressable>)}<Pressable disabled={!location.trim()||addMutation.isPending} onPress={()=>addMutation.mutate()} style={[styles.add,!location.trim()&&styles.disabled]}>{addMutation.isPending?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Add Location</Text>}</Pressable></View>:null}
    {locations.length?<View style={styles.list}><Text style={styles.sectionTitle}>Current locations</Text>{locations.map(item=><View key={item.id} style={styles.locationRow}><Text style={styles.location}>{item.location}</Text><Pressable onPress={()=>setRemoveTarget(item)}><Text style={styles.remove}>Deactivate</Text></Pressable></View>)}</View>:null}
    {message?<Text style={styles.message}>{message}</Text>:null}
    <Modal visible={Boolean(removeTarget)} transparent animationType="fade" onRequestClose={()=>setRemoveTarget(null)}><View style={styles.modalBackdrop}><View style={styles.dialog}><Text style={styles.dialogTitle}>Deactivate location?</Text><Text style={styles.dialogText}>{removeTarget?.location} will stop appearing in active Part Location results.</Text><View style={styles.dialogActions}><Pressable onPress={()=>setRemoveTarget(null)}><Text style={styles.cancel}>Cancel</Text></Pressable><Pressable onPress={()=>removeTarget&&removeMutation.mutate(removeTarget.id)} style={styles.danger}><Text style={styles.primaryText}>Deactivate</Text></Pressable></View></View></View></Modal>
  </Screen>;
}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',padding:spacing.xl,backgroundColor:colors.background},error:{color:colors.danger},back:{color:colors.blue,fontWeight:'800'},searchRow:{flexDirection:'row',gap:spacing.sm},input:{flex:1,minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:spacing.md,backgroundColor:'#fff',color:colors.text},primary:{minWidth:82,minHeight:48,alignItems:'center',justifyContent:'center',paddingHorizontal:spacing.md,borderRadius:radius.md,backgroundColor:colors.navy},primaryText:{color:'#fff',fontSize:12,fontWeight:'900'},verified:{padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.successSoft},verifiedTitle:{color:colors.success,fontSize:16,fontWeight:'900'},verifiedText:{color:colors.text,fontSize:11,marginTop:3},form:{gap:spacing.sm,padding:spacing.lg,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.surface},sectionTitle:{color:colors.text,fontSize:13,fontWeight:'900'},suggestion:{minHeight:40,justifyContent:'center',paddingHorizontal:spacing.md,borderRadius:radius.sm,backgroundColor:colors.surfaceMuted},suggestionText:{color:colors.text,fontSize:11,fontWeight:'700'},add:{minHeight:48,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.navy},disabled:{opacity:.45},list:{gap:spacing.sm},locationRow:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md,padding:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface},location:{flex:1,color:colors.text,fontSize:14,fontWeight:'900'},remove:{color:colors.danger,fontSize:11,fontWeight:'900'},message:{color:colors.navy,fontSize:11,fontWeight:'700'},modalBackdrop:{flex:1,justifyContent:'center',backgroundColor:'rgba(2,6,23,.65)'},dialog:{margin:spacing.xl,padding:spacing.xl,gap:spacing.md,borderRadius:radius.xl,backgroundColor:colors.surface},dialogTitle:{color:colors.text,fontSize:18,fontWeight:'900'},dialogText:{color:colors.textMuted,fontSize:12,lineHeight:18},dialogActions:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:spacing.lg},cancel:{color:colors.textMuted,fontWeight:'800'},danger:{minHeight:44,justifyContent:'center',paddingHorizontal:spacing.lg,borderRadius:radius.md,backgroundColor:colors.danger}});
