import { useMemo, useState } from 'react';
import { router } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { AppIcon } from '@/components/AppIcon';
import { MetricCard } from '@/components/MetricCard';
import { Screen } from '@/components/Screen';
import { StateView } from '@/components/StateView';
import { StatusChip } from '@/components/StatusChip';
import { formatDate } from '@/services/orders';
import { getDelayedVorOrders } from '@/services/operations';
import { colors, radius, spacing } from '@/theme/tokens';

type Bucket='today'|'1-2'|'3-5'|'5+';
export default function DelayedVorScreen(){
 const {role}=useAuth(); const allowed=role!=='accounts'; const [bucket,setBucket]=useState<Bucket>('today'); const [search,setSearch]=useState(''); const query=useQuery({queryKey:['delayed-vor-orders'],queryFn:getDelayedVorOrders,enabled:allowed}); const rows=query.data??[];
 const counts=useMemo(()=>({today:rows.filter(r=>r.age_days===0).length,'1-2':rows.filter(r=>r.age_days>=1&&r.age_days<=2).length,'3-5':rows.filter(r=>r.age_days>=3&&r.age_days<=5).length,'5+':rows.filter(r=>r.age_days>5).length}),[rows]);
 const visible=useMemo(()=>{const n=search.trim().toLowerCase();return rows.filter(r=>bucket==='today'?r.age_days===0:bucket==='1-2'?r.age_days>=1&&r.age_days<=2:bucket==='3-5'?r.age_days>=3&&r.age_days<=5:r.age_days>5).filter(r=>!n||[r.order_no,r.final_order_no,r.branch,r.customer_name,r.machine_no].some(v=>String(v??'').toLowerCase().includes(n)));},[rows,bucket,search]);
 if(!allowed)return <View style={styles.center}><Text style={styles.error}>Delayed VOR is not available for Accounts.</Text></View>;
 return <Screen title="Delayed VOR" subtitle="VOR orders with Processed or Partially Dispatched items, grouped by processing age" scroll={false}><FlatList data={visible} keyExtractor={i=>i.id} refreshing={query.isRefetching} onRefresh={()=>void query.refetch()} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.metrics}><MetricCard label="Today" value={counts.today} active={bucket==='today'} onPress={()=>setBucket('today')}/><MetricCard label="1–2 Days" value={counts['1-2']} active={bucket==='1-2'} onPress={()=>setBucket('1-2')}/><MetricCard label="3–5 Days" value={counts['3-5']} active={bucket==='3-5'} onPress={()=>setBucket('3-5')}/><MetricCard label="More Than 5" value={counts['5+']} active={bucket==='5+'} onPress={()=>setBucket('5+')}/></ScrollView><View style={styles.search}><AppIcon name="search" size={18} color={colors.textMuted}/><TextInput value={search} onChangeText={setSearch} placeholder="Order, branch, customer or machine…" placeholderTextColor={colors.textMuted} style={styles.searchInput}/></View></View>} renderItem={({item})=><Pressable onPress={()=>router.push(`/orders/${item.id}`)} style={({pressed})=>[styles.card,pressed&&styles.pressed]}><View style={styles.top}><View style={styles.copy}><Text style={styles.no}>{item.final_order_no||item.order_no}</Text><Text style={styles.customer}>{item.customer_name||'Customer'} · {item.branch}</Text></View><View style={[styles.age,item.age_days>5&&styles.ageDanger,item.age_days>=3&&item.age_days<=5&&styles.ageWarn]}><Text style={[styles.ageText,item.age_days>5&&styles.ageDangerText]}>{item.age_days===0?'Today':`${item.age_days}d`}</Text></View></View><View style={styles.meta}><Text style={styles.metaText}>Processed {formatDate(item.processed_date)}</Text><Text style={styles.metaText}>{item.machine_no||'No machine'}</Text></View><StatusChip status={item.status}/></Pressable>} ListEmptyComponent={!query.isLoading?(query.isError?<StateView icon="alert" tone="error" title="Delayed VOR could not be loaded" message="Check your connection and try again." actionLabel="Retry" onAction={()=>void query.refetch()}/>:<StateView icon="clock" title="No delayed VOR orders" message="There are no VOR orders in this aging bucket."/>):null}/></Screen>;
}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},error:{color:colors.danger},list:{gap:spacing.sm,paddingBottom:spacing.xxl},header:{gap:spacing.md,marginBottom:spacing.md},metrics:{gap:spacing.sm,paddingRight:spacing.lg},search:{minHeight:48,flexDirection:'row',alignItems:'center',gap:spacing.sm,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:spacing.md,backgroundColor:'#fff'},searchInput:{flex:1,minHeight:46,color:colors.text},card:{gap:spacing.sm,padding:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.surface},pressed:{opacity:.8},top:{flexDirection:'row',justifyContent:'space-between',gap:spacing.sm},copy:{flex:1},no:{color:colors.text,fontSize:14,fontWeight:'900'},customer:{color:colors.textMuted,fontSize:11,marginTop:2},age:{paddingHorizontal:8,paddingVertical:5,borderRadius:radius.sm,backgroundColor:colors.blueSoft},ageWarn:{backgroundColor:colors.warningSoft},ageDanger:{backgroundColor:colors.dangerSoft},ageText:{color:colors.navy,fontSize:10,fontWeight:'900'},ageDangerText:{color:colors.danger},meta:{flexDirection:'row',justifyContent:'space-between',gap:spacing.md},metaText:{color:colors.textMuted,fontSize:10}});
