import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import { ActivityIndicator, FlatList, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '@/auth/AuthProvider';
import { MetricCard } from '@/components/MetricCard';
import { Screen } from '@/components/Screen';
import { formatMoney } from '@/services/orders';
import { getPendingIssueOrders, getPendingIssueParts, markOrderIssued, type PendingIssueOrder } from '@/services/operations';
import { colors, radius, spacing } from '@/theme/tokens';

type AgeFilter='all'|'0-2'|'3-7'|'over-7';
const DOC_TYPES=['DC','Tax Invoice','PI','Manual','Warranty Claim'];
export default function PendingIssueScreen(){
 const {role}=useAuth(); const allowed=['branch','admin','manager','developer','hq'].includes(role??''); const qc=useQueryClient(); const query=useQuery({queryKey:['pending-issue-orders'],queryFn:getPendingIssueOrders,enabled:allowed});
 const [age,setAge]=useState<AgeFilter>('all'); const [type,setType]=useState('all'); const [search,setSearch]=useState(''); const [selected,setSelected]=useState<PendingIssueOrder|null>(null); const [docType,setDocType]=useState('DC'); const [docNo,setDocNo]=useState(''); const [message,setMessage]=useState('');
 const rows=query.data??[]; const counts=useMemo(()=>({all:rows.length,'0-2':rows.filter(r=>r.age_days<=2).length,'3-7':rows.filter(r=>r.age_days>=3&&r.age_days<=7).length,'over-7':rows.filter(r=>r.age_days>7).length,vor:rows.filter(r=>r.order_type.toUpperCase()==='VOR').length,sop:rows.filter(r=>r.order_type.toUpperCase()==='SOP').length}),[rows]);
 const visible=useMemo(()=>{const n=search.trim().toLowerCase();return rows.filter(r=>age==='all'||(age==='0-2'&&r.age_days<=2)||(age==='3-7'&&r.age_days>=3&&r.age_days<=7)||(age==='over-7'&&r.age_days>7)).filter(r=>type==='all'||r.order_type.toLowerCase()===type).filter(r=>!n||[r.order_no,r.final_order_no,r.branch,r.customer_name,r.contact_no,r.machine_no,r.call_id].some(v=>String(v??'').toLowerCase().includes(n)));},[rows,age,type,search]);
 const parts=useQuery({queryKey:['pending-issue-parts',selected?.id],queryFn:()=>getPendingIssueParts(selected!.id),enabled:Boolean(selected)});
 const issue=useMutation({mutationFn:()=>markOrderIssued(selected!.id,docType,docNo),onSuccess:async()=>{setMessage(`${selected?.order_no} marked as Issued.`);setSelected(null);setDocNo('');await query.refetch();await qc.invalidateQueries({queryKey:['orders']});},onError:e=>setMessage(e instanceof Error?e.message:'Could not mark order as issued.')});
 if(!allowed)return <View style={styles.center}><Text style={styles.error}>Pending Issue is not available for this role.</Text></View>;
 return <Screen title="Pending Issue" subtitle="Customer orders fully received but not yet issued" scroll={false}>
   <FlatList data={visible} keyExtractor={i=>i.id} refreshing={query.isRefetching} onRefresh={()=>void query.refetch()} contentContainerStyle={styles.list}
    ListHeaderComponent={<View style={styles.header}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.metrics}><MetricCard label="Total Pending" value={counts.all} active={age==='all'&&type==='all'} onPress={()=>{setAge('all');setType('all')}}/><MetricCard label="0–2 Days" value={counts['0-2']} active={age==='0-2'} onPress={()=>setAge(age==='0-2'?'all':'0-2')}/><MetricCard label="3–7 Days" value={counts['3-7']} active={age==='3-7'} onPress={()=>setAge(age==='3-7'?'all':'3-7')}/><MetricCard label="Over 7 Days" value={counts['over-7']} active={age==='over-7'} onPress={()=>setAge(age==='over-7'?'all':'over-7')}/><MetricCard label="VOR" value={counts.vor} active={type==='vor'} onPress={()=>setType(type==='vor'?'all':'vor')}/><MetricCard label="SOP" value={counts.sop} active={type==='sop'} onPress={()=>setType(type==='sop'?'all':'sop')}/></ScrollView><TextInput value={search} onChangeText={setSearch} placeholder="Order, customer, mobile, machine, call ID…" placeholderTextColor={colors.textMuted} style={styles.input}/>{message?<Text style={styles.message}>{message}</Text>:null}</View>}
    renderItem={({item})=><Pressable onPress={()=>setSelected(item)} style={({pressed})=>[styles.card,pressed&&styles.pressed]}><View style={styles.top}><View style={styles.copy}><Text style={styles.no}>{item.final_order_no||item.order_no}</Text><Text style={styles.customer}>{item.customer_name||'Customer'} · {item.branch}</Text></View><View style={[styles.age,item.age_days>7&&styles.ageDanger]}><Text style={[styles.ageText,item.age_days>7&&styles.ageDangerText]}>{item.age_days===0?'Today':`${item.age_days}d`}</Text></View></View><View style={styles.grid}><Mini label="Type" value={item.order_type}/><Mini label="Qty" value={String(item.total_qty)}/><Mini label="Value" value={formatMoney(item.total_value)}/><Mini label="Received" value={item.received_date?new Date(item.received_date).toLocaleDateString('en-IN'):'—'}/></View></Pressable>}
    ListEmptyComponent={!query.isLoading?<Text style={styles.empty}>{query.isError?'Could not load Pending Issue orders.':'No orders match this filter.'}</Text>:null}/>
   <Modal visible={Boolean(selected)} animationType="slide" onRequestClose={()=>setSelected(null)}><Screen title={selected?.final_order_no||selected?.order_no||'Issue Order'} subtitle="Confirm all received parts, then issue with document reference."><Pressable onPress={()=>setSelected(null)}><Text style={styles.back}>‹ Back</Text></Pressable>{parts.isLoading?<ActivityIndicator color={colors.navy}/>:null}{parts.data?.map(part=><View key={part.id} style={styles.part}><Text style={styles.partNo}>{part.part_no}</Text><Text style={styles.partDesc}>{part.description||'No description'}</Text><View style={styles.partGrid}><Mini label="Required" value={String(part.effective_qty)}/><Mini label="Billed" value={String(part.billed_qty)}/><Mini label="Received" value={String(part.received_qty)}/><Mini label="Status" value={part.item_status}/></View></View>)}<Text style={styles.label}>Issued document type</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{DOC_TYPES.map(v=><Pressable key={v} onPress={()=>setDocType(v)} style={[styles.chip,docType===v&&styles.chipActive]}><Text style={[styles.chipText,docType===v&&styles.chipTextActive]}>{v}</Text></Pressable>)}</ScrollView><Text style={styles.label}>Document No.</Text><TextInput autoCapitalize="characters" value={docNo} onChangeText={setDocNo} placeholder="Required" placeholderTextColor={colors.textMuted} style={styles.input}/><Pressable disabled={!docNo.trim()||issue.isPending} onPress={()=>issue.mutate()} style={[styles.issue,(!docNo.trim()||issue.isPending)&&styles.disabled]}>{issue.isPending?<ActivityIndicator color="#fff"/>:<Text style={styles.issueText}>Mark Order Issued</Text>}</Pressable></Screen></Modal>
 </Screen>;
}
function Mini({label,value}:{label:string;value:string}){return <View style={styles.mini}><Text style={styles.miniLabel}>{label}</Text><Text numberOfLines={1} style={styles.miniValue}>{value}</Text></View>}
const styles=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},error:{color:colors.danger},list:{gap:spacing.sm,paddingBottom:spacing.xxl},header:{gap:spacing.md,marginBottom:spacing.md},metrics:{gap:spacing.sm,paddingRight:spacing.lg},input:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:spacing.md,backgroundColor:'#fff',color:colors.text},message:{color:colors.navy,fontSize:11,fontWeight:'700'},card:{padding:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.surface},pressed:{opacity:.8},top:{flexDirection:'row',justifyContent:'space-between',gap:spacing.sm},copy:{flex:1},no:{color:colors.text,fontSize:14,fontWeight:'900'},customer:{color:colors.textMuted,fontSize:11,marginTop:2},age:{paddingHorizontal:8,paddingVertical:5,borderRadius:radius.sm,backgroundColor:colors.warningSoft},ageText:{color:colors.warning,fontSize:10,fontWeight:'900'},ageDanger:{backgroundColor:colors.dangerSoft},ageDangerText:{color:colors.danger},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,marginTop:spacing.md},mini:{width:'47%'},miniLabel:{color:colors.textMuted,fontSize:9,fontWeight:'700'},miniValue:{color:colors.text,fontSize:11,fontWeight:'800',marginTop:2},empty:{color:colors.textMuted,textAlign:'center',paddingVertical:spacing.xxl},back:{color:colors.blue,fontWeight:'800'},part:{padding:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface},partNo:{color:colors.text,fontSize:13,fontWeight:'900'},partDesc:{color:colors.textMuted,fontSize:10,marginTop:2},partGrid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,marginTop:spacing.sm},label:{color:colors.textMuted,fontSize:9,fontWeight:'900',textTransform:'uppercase'},chips:{gap:spacing.sm,paddingRight:spacing.md},chip:{minHeight:40,justifyContent:'center',paddingHorizontal:spacing.md,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface},chipActive:{backgroundColor:colors.navy,borderColor:colors.navy},chipText:{color:colors.text,fontSize:11,fontWeight:'800'},chipTextActive:{color:'#fff'},issue:{minHeight:52,alignItems:'center',justifyContent:'center',borderRadius:radius.md,backgroundColor:colors.success},issueText:{color:'#fff',fontSize:13,fontWeight:'900'},disabled:{opacity:.45}});
