-- Dealer Price List uploader for production public.part_master.
-- This migration is additive. It does not replace or rewrite part_master during deployment.

alter table public.part_master add column if not exists "HSN" text;
alter table public.part_master add column if not exists "GST" numeric;
alter table public.part_master add column if not exists "Cat2" text;
alter table public.part_master add column if not exists "PartNoNormalized" text;

update public.part_master
set "PartNoNormalized" = upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g'))
where "PartNoNormalized" is distinct from upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g'));

create index if not exists idx_part_master_part_no_normalized on public.part_master ("PartNoNormalized");

create table if not exists public.portal_part_master_uploads (
  id uuid primary key default gen_random_uuid(),
  price_list_month date not null,
  filename text not null,
  status text not null default 'staging' check (status in ('staging','previewed','published','discarded','failed')),
  total_rows integer not null default 0,
  valid_rows integer not null default 0,
  invalid_rows integer not null default 0,
  duplicate_rows integer not null default 0,
  staged_rows integer not null default 0,
  current_parts integer,
  new_parts integer,
  changed_parts integer,
  unchanged_parts integer,
  removed_parts integer,
  uploaded_by uuid not null references public.portal_profiles(id),
  uploaded_at timestamptz not null default now(),
  published_by uuid references public.portal_profiles(id),
  published_at timestamptz,
  last_error text
);

create table if not exists public.portal_part_master_staging (
  id bigint generated by default as identity primary key,
  upload_id uuid not null references public.portal_part_master_uploads(id) on delete cascade,
  source_row integer,
  part_no text not null,
  part_no_normalized text not null,
  description text,
  dnp numeric,
  rtl numeric,
  mrp numeric,
  hsn text,
  gst numeric,
  cat1 text,
  cat2 text,
  created_at timestamptz not null default now(),
  unique (upload_id, part_no_normalized)
);

create table if not exists public.portal_part_master_history (
  id bigint generated by default as identity primary key,
  upload_id uuid not null references public.portal_part_master_uploads(id) on delete cascade,
  price_list_month date not null,
  part_no text not null,
  part_no_normalized text not null,
  description text,
  dnp numeric,
  rtl numeric,
  mrp numeric,
  hsn text,
  gst numeric,
  cat1 text,
  cat2 text,
  published_at timestamptz not null,
  unique (upload_id, part_no_normalized)
);

create index if not exists idx_portal_part_master_staging_upload on public.portal_part_master_staging(upload_id);
create index if not exists idx_portal_part_master_history_part_month on public.portal_part_master_history(part_no_normalized, price_list_month desc);

alter table public.portal_part_master_uploads enable row level security;
alter table public.portal_part_master_staging enable row level security;
alter table public.portal_part_master_history enable row level security;

revoke all on public.portal_part_master_uploads from anon, authenticated;
revoke all on public.portal_part_master_staging from anon, authenticated;
revoke all on public.portal_part_master_history from anon, authenticated;

create or replace function public.portal_price_master_actor()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
  v_role text;
begin
  select id, role into v_profile_id, v_role
  from public.portal_profiles
  where auth_user_id = auth.uid()
    and coalesce(is_active, false) = true
  limit 1;

  if v_profile_id is null or v_role not in ('admin', 'developer') then
    raise exception 'Only active Admin or Developer users can manage the Dealer Price List';
  end if;

  return v_profile_id;
end;
$$;

revoke all on function public.portal_price_master_actor() from public, anon, authenticated;

create or replace function public.portal_start_part_master_upload(
  p_price_list_month date,
  p_filename text,
  p_total_rows integer,
  p_valid_rows integer,
  p_invalid_rows integer default 0,
  p_duplicate_rows integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid := public.portal_price_master_actor();
  v_upload_id uuid;
begin
  if p_price_list_month is null then raise exception 'Price list month is required'; end if;
  if coalesce(trim(p_filename), '') = '' then raise exception 'Filename is required'; end if;
  if coalesce(p_valid_rows, 0) <= 0 then raise exception 'No valid price-list rows found'; end if;

  insert into public.portal_part_master_uploads (
    price_list_month, filename, total_rows, valid_rows, invalid_rows, duplicate_rows, uploaded_by
  ) values (
    date_trunc('month', p_price_list_month)::date, trim(p_filename), coalesce(p_total_rows,0), coalesce(p_valid_rows,0), coalesce(p_invalid_rows,0), coalesce(p_duplicate_rows,0), v_profile_id
  ) returning id into v_upload_id;

  return jsonb_build_object('ok', true, 'uploadId', v_upload_id);
end;
$$;

create or replace function public.portal_stage_part_master_chunk(p_upload_id uuid, p_rows jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid := public.portal_price_master_actor();
  v_owner uuid;
  v_status text;
  v_count integer;
begin
  select uploaded_by, status into v_owner, v_status from public.portal_part_master_uploads where id = p_upload_id for update;
  if v_owner is null then raise exception 'Price-list upload session not found'; end if;
  if v_owner <> v_profile_id then raise exception 'This upload session belongs to another user'; end if;
  if v_status <> 'staging' then raise exception 'This upload is no longer accepting rows'; end if;
  if jsonb_typeof(p_rows) <> 'array' then raise exception 'Rows must be a JSON array'; end if;

  insert into public.portal_part_master_staging (
    upload_id, source_row, part_no, part_no_normalized, description, dnp, rtl, mrp, hsn, gst, cat1, cat2
  )
  select
    p_upload_id,
    nullif(r.value->>'source_row','')::integer,
    upper(regexp_replace(trim(r.value->>'part_no'), '\s+', '', 'g')),
    upper(regexp_replace(trim(r.value->>'part_no_normalized'), '\s+', '', 'g')),
    nullif(trim(r.value->>'description'), ''),
    nullif(r.value->>'dnp','')::numeric,
    nullif(r.value->>'rtl','')::numeric,
    nullif(r.value->>'mrp','')::numeric,
    nullif(trim(r.value->>'hsn'), ''),
    nullif(r.value->>'gst','')::numeric,
    nullif(trim(r.value->>'cat1'), ''),
    nullif(trim(r.value->>'cat2'), '')
  from jsonb_array_elements(p_rows) r(value)
  on conflict (upload_id, part_no_normalized) do update set
    source_row = excluded.source_row,
    part_no = excluded.part_no,
    description = excluded.description,
    dnp = excluded.dnp,
    rtl = excluded.rtl,
    mrp = excluded.mrp,
    hsn = excluded.hsn,
    gst = excluded.gst,
    cat1 = excluded.cat1,
    cat2 = excluded.cat2;

  select count(*) into v_count from public.portal_part_master_staging where upload_id = p_upload_id;
  update public.portal_part_master_uploads set staged_rows = v_count where id = p_upload_id;
  return jsonb_build_object('ok', true, 'stagedRows', v_count);
end;
$$;

create or replace function public.portal_preview_part_master_upload(p_upload_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid := public.portal_price_master_actor();
  v_owner uuid;
  v_status text;
  v_valid integer;
  v_invalid integer;
  v_duplicates integer;
  v_current integer;
  v_staged integer;
  v_new integer;
  v_changed integer;
  v_unchanged integer;
  v_removed integer;
  v_blocked boolean := false;
  v_warnings jsonb := '[]'::jsonb;
  v_changed_sample jsonb;
  v_new_sample jsonb;
  v_removed_sample jsonb;
begin
  select uploaded_by, status, valid_rows, invalid_rows, duplicate_rows
    into v_owner, v_status, v_valid, v_invalid, v_duplicates
  from public.portal_part_master_uploads where id = p_upload_id for update;

  if v_owner is null then raise exception 'Price-list upload session not found'; end if;
  if v_owner <> v_profile_id then raise exception 'This upload session belongs to another user'; end if;
  if v_status not in ('staging','previewed') then raise exception 'This upload cannot be previewed'; end if;

  select count(*) into v_staged from public.portal_part_master_staging where upload_id = p_upload_id;
  select count(distinct upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g'))) into v_current from public.part_master where coalesce(trim("PartNo"),'') <> '';

  with current_parts as (
    select distinct on (upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')))
      upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')) as key,
      "Description" as description, "DNP" as dnp, "RTL" as rtl, "MRP" as mrp, "HSN" as hsn, "GST" as gst, "Cat1" as cat1, "Cat2" as cat2
    from public.part_master
    where coalesce(trim("PartNo"),'') <> ''
    order by upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')), ctid
  ), comparison as (
    select s.*, c.key as current_key, c.description as old_description, c.dnp as old_dnp, c.rtl as old_rtl, c.mrp as old_mrp, c.hsn as old_hsn, c.gst as old_gst, c.cat1 as old_cat1, c.cat2 as old_cat2,
      (c.key is not null and (
        coalesce(c.description,'') is distinct from coalesce(s.description,'') or
        c.dnp is distinct from s.dnp or c.rtl is distinct from s.rtl or c.mrp is distinct from s.mrp or
        coalesce(c.hsn,'') is distinct from coalesce(s.hsn,'') or c.gst is distinct from s.gst or
        coalesce(c.cat1,'') is distinct from coalesce(s.cat1,'') or coalesce(c.cat2,'') is distinct from coalesce(s.cat2,'')
      )) as is_changed
    from public.portal_part_master_staging s left join current_parts c on c.key = s.part_no_normalized
    where s.upload_id = p_upload_id
  )
  select
    count(*) filter (where current_key is null),
    count(*) filter (where current_key is not null and is_changed),
    count(*) filter (where current_key is not null and not is_changed)
  into v_new, v_changed, v_unchanged
  from comparison;

  with current_parts as (
    select distinct upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')) as key
    from public.part_master where coalesce(trim("PartNo"),'') <> ''
  )
  select count(*) into v_removed
  from current_parts c
  where not exists (select 1 from public.portal_part_master_staging s where s.upload_id = p_upload_id and s.part_no_normalized = c.key);

  if v_staged <> v_valid then
    v_blocked := true;
    v_warnings := v_warnings || jsonb_build_array(format('Staged row count %s does not match validated row count %s.', v_staged, v_valid));
  end if;
  if coalesce(v_invalid,0) > 0 or coalesce(v_duplicates,0) > 0 then
    v_blocked := true;
    v_warnings := v_warnings || jsonb_build_array('Invalid or duplicate rows must be resolved before publishing.');
  end if;
  if v_current >= 1000 and v_staged < (v_current * 0.50) then
    v_blocked := true;
    v_warnings := v_warnings || jsonb_build_array(format('Safety block: the staged list has %s parts versus %s currently active parts.', v_staged, v_current));
  end if;
  if v_removed > 0 then
    v_warnings := v_warnings || jsonb_build_array(format('%s currently active part(s) are missing from the new complete snapshot and will be removed from the active master on publish.', v_removed));
  end if;

  with current_parts as (
    select distinct on (upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')))
      upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')) as key,
      "Description" as description, "DNP" as dnp, "RTL" as rtl, "MRP" as mrp
    from public.part_master where coalesce(trim("PartNo"),'') <> ''
    order by upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')), ctid
  )
  select coalesce(jsonb_agg(x), '[]'::jsonb) into v_changed_sample from (
    select jsonb_build_object('partNo',s.part_no,'description',s.description,'oldDnp',c.dnp,'newDnp',s.dnp,'oldRtl',c.rtl,'newRtl',s.rtl,'oldMrp',c.mrp,'newMrp',s.mrp) x
    from public.portal_part_master_staging s join current_parts c on c.key=s.part_no_normalized
    where s.upload_id=p_upload_id and (c.dnp is distinct from s.dnp or c.rtl is distinct from s.rtl or c.mrp is distinct from s.mrp or coalesce(c.description,'') is distinct from coalesce(s.description,''))
    order by s.part_no limit 50
  ) q;

  with current_parts as (
    select distinct upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')) as key from public.part_master where coalesce(trim("PartNo"),'') <> ''
  )
  select coalesce(jsonb_agg(x), '[]'::jsonb) into v_new_sample from (
    select jsonb_build_object('partNo',s.part_no,'description',s.description,'newDnp',s.dnp) x
    from public.portal_part_master_staging s left join current_parts c on c.key=s.part_no_normalized
    where s.upload_id=p_upload_id and c.key is null order by s.part_no limit 50
  ) q;

  with current_parts as (
    select distinct on (upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')))
      upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')) as key, "PartNo" as part_no, "Description" as description, "DNP" as dnp
    from public.part_master where coalesce(trim("PartNo"),'') <> ''
    order by upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')), ctid
  )
  select coalesce(jsonb_agg(x), '[]'::jsonb) into v_removed_sample from (
    select jsonb_build_object('partNo',c.part_no,'description',c.description,'newDnp',c.dnp) x
    from current_parts c where not exists (select 1 from public.portal_part_master_staging s where s.upload_id=p_upload_id and s.part_no_normalized=c.key)
    order by c.part_no limit 50
  ) q;

  update public.portal_part_master_uploads set status='previewed', staged_rows=v_staged, current_parts=v_current, new_parts=v_new, changed_parts=v_changed, unchanged_parts=v_unchanged, removed_parts=v_removed where id=p_upload_id;

  return jsonb_build_object('ok',true,'uploadId',p_upload_id,'currentParts',v_current,'stagedParts',v_staged,'newParts',v_new,'changedParts',v_changed,'unchangedParts',v_unchanged,'removedParts',v_removed,'publishBlocked',v_blocked,'warnings',v_warnings,'changedSample',v_changed_sample,'newSample',v_new_sample,'removedSample',v_removed_sample);
end;
$$;

create or replace function public.portal_publish_part_master_upload(p_upload_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid := public.portal_price_master_actor();
  v_owner uuid;
  v_status text;
  v_month date;
  v_valid integer;
  v_staged integer;
  v_current integer;
  v_published_at timestamptz := now();
begin
  select uploaded_by, status, price_list_month, valid_rows into v_owner, v_status, v_month, v_valid
  from public.portal_part_master_uploads where id=p_upload_id for update;
  if v_owner is null then raise exception 'Price-list upload session not found'; end if;
  if v_owner <> v_profile_id then raise exception 'This upload session belongs to another user'; end if;
  if v_status <> 'previewed' then raise exception 'Preview the price list before publishing'; end if;

  select count(*) into v_staged from public.portal_part_master_staging where upload_id=p_upload_id;
  if v_staged <> v_valid or v_staged <= 0 then raise exception 'Staged rows are incomplete; publication cancelled'; end if;

  -- Readers keep AccessShare locks; this lock blocks competing writes without taking the portal offline.
  lock table public.part_master in share row exclusive mode;

  -- Remove legacy duplicates by normalized key before synchronizing the new complete snapshot.
  delete from public.part_master p
  using (
    select ctid, row_number() over (partition by upper(regexp_replace(coalesce("PartNo", ''), '\s+', '', 'g')) order by ctid) rn
    from public.part_master where coalesce(trim("PartNo"),'') <> ''
  ) d
  where p.ctid=d.ctid and d.rn>1;

  update public.part_master p set
    "PartNo"=s.part_no,
    "PartNoNormalized"=s.part_no_normalized,
    "Description"=s.description,
    "DNP"=s.dnp,
    "RTL"=s.rtl,
    "MRP"=s.mrp,
    "HSN"=s.hsn,
    "GST"=s.gst,
    "Cat1"=s.cat1,
    "Cat2"=s.cat2
  from public.portal_part_master_staging s
  where s.upload_id=p_upload_id
    and upper(regexp_replace(coalesce(p."PartNo", ''), '\s+', '', 'g'))=s.part_no_normalized;

  insert into public.part_master ("PartNo","PartNoNormalized","Description","DNP","RTL","MRP","HSN","GST","Cat1","Cat2")
  select s.part_no,s.part_no_normalized,s.description,s.dnp,s.rtl,s.mrp,s.hsn,s.gst,s.cat1,s.cat2
  from public.portal_part_master_staging s
  where s.upload_id=p_upload_id
    and not exists (select 1 from public.part_master p where p."PartNoNormalized"=s.part_no_normalized);

  delete from public.part_master p
  where coalesce(p."PartNoNormalized", upper(regexp_replace(coalesce(p."PartNo", ''), '\s+', '', 'g'))) <> ''
    and not exists (
      select 1 from public.portal_part_master_staging s
      where s.upload_id=p_upload_id and s.part_no_normalized=coalesce(p."PartNoNormalized", upper(regexp_replace(coalesce(p."PartNo", ''), '\s+', '', 'g')))
    );

  delete from public.portal_part_master_history where upload_id=p_upload_id;
  insert into public.portal_part_master_history (upload_id,price_list_month,part_no,part_no_normalized,description,dnp,rtl,mrp,hsn,gst,cat1,cat2,published_at)
  select p_upload_id,v_month,s.part_no,s.part_no_normalized,s.description,s.dnp,s.rtl,s.mrp,s.hsn,s.gst,s.cat1,s.cat2,v_published_at
  from public.portal_part_master_staging s where s.upload_id=p_upload_id;

  select count(*) into v_current from public.part_master;
  update public.portal_part_master_uploads set status='published', published_by=v_profile_id, published_at=v_published_at where id=p_upload_id;
  return jsonb_build_object('ok',true,'uploadId',p_upload_id,'activeParts',v_current,'publishedAt',v_published_at);
exception when others then
  update public.portal_part_master_uploads set last_error=sqlerrm where id=p_upload_id;
  raise;
end;
$$;

create or replace function public.portal_discard_part_master_upload(p_upload_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid := public.portal_price_master_actor();
  v_owner uuid;
  v_status text;
begin
  select uploaded_by,status into v_owner,v_status from public.portal_part_master_uploads where id=p_upload_id for update;
  if v_owner is null then return jsonb_build_object('ok',true); end if;
  if v_owner <> v_profile_id then raise exception 'This upload session belongs to another user'; end if;
  if v_status='published' then raise exception 'Published price lists cannot be discarded'; end if;
  delete from public.portal_part_master_staging where upload_id=p_upload_id;
  update public.portal_part_master_uploads set status='discarded' where id=p_upload_id;
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.portal_list_part_master_uploads(p_limit integer default 6)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.portal_price_master_actor();
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',u.id,'priceListMonth',u.price_list_month,'filename',u.filename,'status',u.status,'validRows',u.valid_rows,'uploadedAt',u.uploaded_at,'publishedAt',u.published_at
    ) order by u.uploaded_at desc)
    from (select * from public.portal_part_master_uploads order by uploaded_at desc limit greatest(1,least(coalesce(p_limit,6),20))) u
  ), '[]'::jsonb);
end;
$$;

revoke all on function public.portal_start_part_master_upload(date,text,integer,integer,integer,integer) from public, anon;
revoke all on function public.portal_stage_part_master_chunk(uuid,jsonb) from public, anon;
revoke all on function public.portal_preview_part_master_upload(uuid) from public, anon;
revoke all on function public.portal_publish_part_master_upload(uuid) from public, anon;
revoke all on function public.portal_discard_part_master_upload(uuid) from public, anon;
revoke all on function public.portal_list_part_master_uploads(integer) from public, anon;

grant execute on function public.portal_start_part_master_upload(date,text,integer,integer,integer,integer) to authenticated;
grant execute on function public.portal_stage_part_master_chunk(uuid,jsonb) to authenticated;
grant execute on function public.portal_preview_part_master_upload(uuid) to authenticated;
grant execute on function public.portal_publish_part_master_upload(uuid) to authenticated;
grant execute on function public.portal_discard_part_master_upload(uuid) to authenticated;
grant execute on function public.portal_list_part_master_uploads(integer) to authenticated;
